<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoilManager.Application\CoilManager.Application.csproj" />
    <ProjectReference Include="..\CoilManager.Domain\CoilManager.Domain.csproj" />
    <ProjectReference Include="..\CoilManager.Shared\CoilManager.Shared.csproj" />
  </ItemGroup>

</Project>
