using CoilManager.Application.DTOs.LaminationJobs;
using CoilManager.Application.Interfaces.Services;
using CoilManager.Domain.Entities;
using CoilManager.Domain.Enums;
using CoilManager.Shared.Exceptions;
using CoilManager.Shared.Pagination;
using Microsoft.EntityFrameworkCore;

namespace CoilManager.Persistence.Services;
public sealed class LaminationJobService(ApplicationDbContext db, ICurrentUserService user) : IMaterialAllocationService
{
 const decimal WidthTolerance=0.10m;
 IQueryable<LaminationJob> Jobs(bool graph=false) { var q=db.LaminationJobs.Include(x=>x.Grade).AsQueryable(); return graph?q.Include(x=>x.Steps).ThenInclude(x=>x.Plates).ThenInclude(x=>x.Dimensions).Include(x=>x.Allocations):q; }
 public async Task<PagedResult<LaminationJobListItemDto>> GetAsync(LaminationJobQueryRequest r,CancellationToken t=default) { var q=Jobs(); if(!string.IsNullOrWhiteSpace(r.Search)) q=q.Where(x=>x.LaminationJobNumber.Contains(r.Search)||x.Rating.Contains(r.Search)||(x.JobOrDrawingNumber!=null&&x.JobOrDrawingNumber.Contains(r.Search))||(x.Customer!=null&&x.Customer.Contains(r.Search))); if(r.Status.HasValue)q=q.Where(x=>x.Status==r.Status); if(r.DesignType.HasValue)q=q.Where(x=>x.DesignType==r.DesignType); if(r.GradeId.HasValue)q=q.Where(x=>x.GradeId==r.GradeId); if(r.PlannedFrom.HasValue)q=q.Where(x=>x.PlannedDate>=r.PlannedFrom); if(r.PlannedTo.HasValue)q=q.Where(x=>x.PlannedDate<=r.PlannedTo); if(!string.IsNullOrWhiteSpace(r.Customer))q=q.Where(x=>x.Customer!=null&&x.Customer.Contains(r.Customer)); if(!string.IsNullOrWhiteSpace(r.Rating))q=q.Where(x=>x.Rating.Contains(r.Rating)); int count=await q.CountAsync(t); int page=Math.Max(1,r.PageNumber),size=Math.Clamp(r.PageSize,1,100); var rows=await q.OrderByDescending(x=>x.CreatedAtUtc).Skip((page-1)*size).Take(size).ToListAsync(t); return new(rows.Select(List).ToArray(),page,size,count); }
 public async Task<LaminationJobDetailsDto> GetAsync(Guid id,CancellationToken t=default)=>Map(await Find(id,t));
 public async Task<LaminationJobDetailsDto> GetByNumberAsync(string n,CancellationToken t=default)=>Map(await Jobs(true).SingleOrDefaultAsync(x=>x.LaminationJobNumber==n,t)??throw new NotFoundException("Lamination Job was not found."));
 public async Task<string> GetNextNumberAsync(CancellationToken t=default) { int y=DateTime.UtcNow.Year; string prefix=$"AE/C/{y}/"; string? last=await db.LaminationJobs.IgnoreQueryFilters().Where(x=>x.LaminationJobNumber.StartsWith(prefix)).OrderByDescending(x=>x.LaminationJobNumber).Select(x=>x.LaminationJobNumber).FirstOrDefaultAsync(t); int seq=last is null?1:int.Parse(last[^5..])+1; return FormatNumber(y,seq); }
 public static string FormatNumber(int year,int sequence)=>LaminationJob.FormatNumber(year,sequence);
 public async Task<LaminationJobDetailsDto> CreateAsync(CreateLaminationJobRequest r,CancellationToken t=default) { Grade grade=await SuitableGrade(r.GradeId,r.CustomerCategory,r.CustomerCoreLossPerKg,t); LaminationJob? job=null; await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,t); string number=await GetNextNumberAsync(t); job=new(number,r.JobOrDrawingNumber,r.Customer,r.Rating,r.DesignType,r.StepLapOrientation,r.NumberOfSteps,r.GradeId,grade.ThicknessMm,grade.Category,grade.CoreLossPerKg,r.TotalWeight,r.CustomerCoreLossPerKg,r.WorkOrderId,r.WorkOrderNumber,r.PlannedDate,r.RequiredDate,r.Shift,r.PlannerName,r.Remarks); foreach(var s in r.Steps)job.AddStep(Build(s)); job.SetCreatedAudit(Actor(),DateTimeOffset.UtcNow); db.Add(job); await db.SaveChangesAsync(t); await tx.CommitAsync(t); return Map(job); }
 public async Task<LaminationJobDetailsDto> UpdateAsync(Guid id,UpdateLaminationJobRequest r,CancellationToken t=default)
 {
  await using var tx=await db.Database.BeginTransactionAsync(t);
  var current=await Find(id,t);
  Grade grade=await SuitableGrade(r.GradeId,r.CustomerCategory,r.CustomerCoreLossPerKg,t);
  var replacementSteps=r.Steps.Select(Build).ToArray();

  await db.LaminationJobSteps.Where(x=>x.LaminationJobId==id).ExecuteDeleteAsync(t);
  db.ChangeTracker.Clear();

  var j=await Jobs().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new NotFoundException("Lamination Job was not found.");
  if(!string.IsNullOrWhiteSpace(r.RowVersion))db.Entry(j).Property(x=>x.RowVersion).OriginalValue=Convert.FromBase64String(r.RowVersion);
  j.UpdatePlanning(r.JobOrDrawingNumber,r.Customer,r.Rating,r.DesignType,r.StepLapOrientation,r.NumberOfSteps,r.GradeId,grade.ThicknessMm,grade.Category,grade.CoreLossPerKg,r.TotalWeight,r.CustomerCoreLossPerKg,r.WorkOrderId,r.WorkOrderNumber,r.PlannedDate,r.RequiredDate,r.Shift,r.PlannerName,r.Remarks);
  j.ReplaceSchedule(replacementSteps);
  db.AddRange(replacementSteps);
  await db.SaveChangesAsync(t);
  await tx.CommitAsync(t);
  return Map(j);
 }
 public async Task DeleteAsync(Guid id,CancellationToken t=default) { var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Draft)throw new BusinessRuleException("Only Draft jobs can be deleted."); db.Remove(j); await db.SaveChangesAsync(t); }
 public async Task SetDrawingAsync(Guid id,string name,string reference,CancellationToken t=default){var j=await Find(id,t);j.SetAttachment(name,reference);await db.SaveChangesAsync(t);}
 public async Task<(string Name,string Reference)> GetDrawingAsync(Guid id,CancellationToken t=default){var j=await Find(id,t);if(string.IsNullOrWhiteSpace(j.DrawingAttachmentPath))throw new NotFoundException("Drawing attachment was not found.");return(j.DrawingAttachmentName!,j.DrawingAttachmentPath);}
 public async Task<string?> DeleteDrawingAsync(Guid id,CancellationToken t=default){var j=await Find(id,t);string? path=j.DrawingAttachmentPath;j.ClearAttachment();await db.SaveChangesAsync(t);return path;}
 public async Task<IReadOnlyList<LaminationMaterialRequirementDto>> RequirementsAsync(Guid id,CancellationToken t=default) { var j=await Find(id,t); return Requirements(j); }
 public async Task<IReadOnlyList<AvailableSlitCoilDto>> AvailableAsync(Guid id,AvailableSlitCoilQueryRequest r,CancellationToken t=default)
 {
  _=await Find(id,t);
  var reservations=await db.LaminationJobMaterialAllocations
   .Where(a=>a.Status==AllocationStatus.Reserved)
   .GroupBy(a=>a.SlitCoilId)
   .Select(g=>new{Id=g.Key,Weight=g.Sum(a=>a.AllocatedWeight)})
   .ToDictionaryAsync(x=>x.Id,x=>x.Weight,t);
  var q=db.SlitCoils.Include(x=>x.Grade).Include(x=>x.MotherCoil).Include(x=>x.SlittingJob)
   .Where(c=>c.Status==CoilStatus.Available&&c.Weight>0);
  if(!string.IsNullOrWhiteSpace(r.Search))q=q.Where(c=>c.CoilNumber.Contains(r.Search)||(c.MotherCoil!=null&&c.MotherCoil.RawCoilNumber.Contains(r.Search)));
  if(r.Width.HasValue)q=q.Where(c=>c.Width==r.Width.Value);
  if(!string.IsNullOrWhiteSpace(r.Grade))q=q.Where(c=>c.Grade!=null&&c.Grade.Code==r.Grade);
  if(r.Thickness.HasValue)q=q.Where(c=>c.Thickness==r.Thickness.Value);
  if(!string.IsNullOrWhiteSpace(r.Warehouse))q=q.Where(c=>c.WarehouseLocation!=null&&c.WarehouseLocation.Contains(r.Warehouse));
  var coils=await q.OrderBy(c=>c.Width).ThenBy(c=>c.CreatedAtUtc).ToListAsync(t);
  return coils.Select(c=>{decimal reserved=reservations.GetValueOrDefault(c.Id);decimal available=c.Weight-reserved;return new{c,reserved,available};})
   .Where(x=>x.available>0&&(!r.AvailableWeight.HasValue||x.available>=r.AvailableWeight.Value))
   .Select(x=>new AvailableSlitCoilDto(x.c.Id,x.c.CoilNumber,x.c.MotherCoil?.RawCoilNumber,x.c.Grade?.Code??"",x.c.Thickness,x.c.Category,x.c.CoreLossPerKg,x.c.Width,x.c.Weight,x.reserved,x.available,x.c.Status.ToString(),x.c.WarehouseLocation,x.c.SlittingJob?.SlittingJobNo,x.c.CreatedAtUtc)).ToArray();
 }
 public async Task<IReadOnlyList<LaminationJobMaterialAllocationDto>> AllocationsAsync(Guid id,CancellationToken t=default) { var allocations=(await Find(id,t)).Allocations.OrderByDescending(x=>x.ReservedOn).ToArray(); var ids=allocations.Select(x=>x.SlitCoilId).Distinct().ToArray(); var losses=await db.SlitCoils.Where(x=>ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.CoreLossPerKg,t); return allocations.Select(x=>MapAllocation(x,losses.GetValueOrDefault(x.SlitCoilId))).ToArray(); }
 public async Task<LaminationJobMaterialAllocationDto> AllocateAsync(Guid id,CreateLaminationAllocationRequest r,CancellationToken t=default) { if(r.AllocatedWeight<=0)throw new BusinessRuleException("Allocated Weight must be greater than zero."); await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,t); var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Released)throw new BusinessRuleException("Material allocation is allowed only after the Lamination Job is Released."); var c=await db.SlitCoils.SingleOrDefaultAsync(x=>x.Id==r.SlitCoilId,t)??throw new NotFoundException("Slit Coil was not found."); if(c.Status!=CoilStatus.Available||c.Thickness!=j.Thickness)throw new BusinessRuleException("Slit Coil must be available and match Thickness."); bool partialMatch=Math.Abs(c.Width-r.RequiredWidth)>WidthTolerance||c.CoreLossPerKg!=j.CoreLossPerKg; if(partialMatch&&(!r.WidthMismatchOverride||string.IsNullOrWhiteSpace(r.OverrideReason)))throw new BusinessRuleException("A Partial Match allocation requires confirmation and a reason."); var requirement=Requirements(j).SingleOrDefault(x=>Math.Abs(x.Width-r.RequiredWidth)<=WidthTolerance)??throw new BusinessRuleException("The selected material requirement does not exist."); decimal reserved=await db.LaminationJobMaterialAllocations.Where(x=>x.SlitCoilId==c.Id&&x.Status==AllocationStatus.Reserved).SumAsync(x=>(decimal?)x.AllocatedWeight,t)??0; decimal available=c.Weight-reserved; if(r.AllocatedWeight>available)throw new BusinessRuleException($"Allocation weight cannot exceed the coil's available weight of {available:N2} kg."); if(r.AllocatedWeight>requirement.ShortageWeight)throw new BusinessRuleException($"The remaining requirement is only {requirement.ShortageWeight:N2} kg."); var a=new LaminationJobMaterialAllocation(j.Id,c.Id,c.CoilNumber,r.RequiredWidth,r.AllocatedWeight,available-r.AllocatedWeight,Actor(),DateTimeOffset.UtcNow,partialMatch?$"PARTIAL MATCH OVERRIDE: {r.OverrideReason}. {r.Remarks}":r.Remarks); j.Allocations.Add(a); db.Entry(a).State=EntityState.Added; j.Recalculate(); await db.SaveChangesAsync(t); await tx.CommitAsync(t); return MapAllocation(a,c.CoreLossPerKg); }
 public async Task<LaminationJobMaterialAllocationDto> UpdateAllocationAsync(Guid id,Guid allocationId,UpdateLaminationAllocationRequest r,CancellationToken t=default)
 {
  if(r.AllocatedWeight<=0)throw new BusinessRuleException("Allocated Weight must be greater than zero.");
  await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,t);
  var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Released)throw new BusinessRuleException("Allocations can be edited only while the job is Released.");
  var a=j.Allocations.SingleOrDefault(x=>x.Id==allocationId)??throw new NotFoundException("Allocation was not found.");
  if(a.Status!=AllocationStatus.Reserved)throw new BusinessRuleException("Only active reservations can be edited.");
  var c=await db.SlitCoils.SingleOrDefaultAsync(x=>x.Id==a.SlitCoilId,t)??throw new NotFoundException("Slit Coil was not found.");
  decimal reservedByOthers=await db.LaminationJobMaterialAllocations.Where(x=>x.SlitCoilId==c.Id&&x.Status==AllocationStatus.Reserved&&x.Id!=a.Id).SumAsync(x=>(decimal?)x.AllocatedWeight,t)??0;
  decimal availableToAllocation=c.Weight-reservedByOthers;
  if(r.AllocatedWeight>availableToAllocation)throw new BusinessRuleException($"Allocation weight cannot exceed the coil's available weight of {availableToAllocation:N2} kg.");
  var requirement=Requirements(j).SingleOrDefault(x=>Math.Abs(x.Width-a.RequiredWidth)<=WidthTolerance)??throw new BusinessRuleException("The selected material requirement does not exist.");
  decimal maximumRequirement=requirement.RequiredWeight-(requirement.AllocatedWeight-a.AllocatedWeight);
  if(r.AllocatedWeight>maximumRequirement)throw new BusinessRuleException($"The remaining requirement allows a maximum allocation of {maximumRequirement:N2} kg.");
  a.Adjust(r.AllocatedWeight,availableToAllocation-r.AllocatedWeight,Actor(),DateTimeOffset.UtcNow,r.Remarks); j.Recalculate();
  await db.SaveChangesAsync(t); await tx.CommitAsync(t); return MapAllocation(a);
 } public async Task ReleaseAllocationAsync(Guid id,Guid allocationId,CancellationToken t=default) { var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Released)throw new BusinessRuleException("Allocations can be changed only while the job is Released."); var a=j.Allocations.SingleOrDefault(x=>x.Id==allocationId)??throw new NotFoundException("Allocation was not found."); a.Release(Actor(),DateTimeOffset.UtcNow); j.Recalculate(); await db.SaveChangesAsync(t); }
 public async Task<LaminationJobDetailsDto> ConfirmAsync(Guid id,ConfirmLaminationAllocationRequest r,CancellationToken t=default) { var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Released)throw new BusinessRuleException("Only a Released job can confirm material allocation."); var req=Requirements(j); if(req.Count==0||!j.Allocations.Any(x=>x.Status==AllocationStatus.Reserved))throw new BusinessRuleException("At least one material requirement and allocation is required."); if(req.Any(x=>x.ShortageWeight>0)&&(!r.ShortageOverride||string.IsNullOrWhiteSpace(r.OverrideReason)))throw new BusinessRuleException("Material shortage must be zero before allocation confirmation."); j.ConfirmAllocation(Actor(),DateTimeOffset.UtcNow); await db.SaveChangesAsync(t); return Map(j); }
 public async Task<LaminationJobDetailsDto> SkipAllocationAsync(Guid id,CancellationToken t=default) { var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Released)throw new BusinessRuleException("Only a Released job can skip material allocation."); if(j.Allocations.Any(x=>x.Status==AllocationStatus.Reserved))throw new BusinessRuleException("Material allocation cannot be skipped after inventory has been reserved."); j.ConfirmAllocation(Actor(),DateTimeOffset.UtcNow); await db.SaveChangesAsync(t); return Map(j); }
 public async Task<LaminationJobDetailsDto> ReleaseAsync(Guid id,ReleaseLaminationJobRequest r,CancellationToken t=default) { var j=await Find(id,t); if(j.Status!=LaminationJobStatus.Draft)throw new BusinessRuleException("Only a Draft job can be released."); j.Release(Actor(),DateTimeOffset.UtcNow); await db.SaveChangesAsync(t); return Map(j); }
 public async Task<LaminationJobDetailsDto> CompleteAsync(Guid id,CompleteLaminationJobRequest r,CancellationToken t=default)
 {
  await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,t);
  var j=await Find(id,t);
  if(j.Status!=LaminationJobStatus.Allocated)throw new BusinessRuleException("Only an Allocated Lamination Job can be completed.");
  if(!string.IsNullOrWhiteSpace(r.RowVersion))db.Entry(j).Property(x=>x.RowVersion).OriginalValue=Convert.FromBase64String(r.RowVersion);
  var active=j.Allocations.Where(x=>x.Status==AllocationStatus.Reserved).ToArray();
  var manual=r.ManualAllocations??[];
  if(active.Length==0&&r.Allocations.Count!=0)throw new BusinessRuleException("A manually issued job must not include reservation allocations.");
  if(active.Length==0&&manual.Select(x=>x.SlitCoilId).Distinct().Count()!=manual.Count)throw new BusinessRuleException("Select each manually used Slit Coil at most once.");
  if(active.Length>0&&manual.Count>0)throw new BusinessRuleException("Manual Slit Coils are allowed only when planner allocation was skipped.");
  if(active.Length>0&&(r.Allocations.Count!=active.Length||r.Allocations.Select(x=>x.AllocationId).Distinct().Count()!=active.Length||active.Any(x=>!r.Allocations.Any(y=>y.AllocationId==x.Id))))throw new BusinessRuleException("Every active allocation must be included exactly once.");
  if(r.PlateResults.Any(x=>x.GoodQuantity<0||x.RejectedQuantity<0||x.GoodQuantity+x.RejectedQuantity>x.PlannedQuantity))throw new BusinessRuleException("Plate result quantities are invalid.");
  decimal total=active.Length>0?r.Allocations.Sum(x=>x.ActualConsumedWeight):manual.Sum(x=>x.ActualConsumedWeight);
  if(total!=r.TotalConsumedWeight||(active.Length>0&&total>active.Sum(x=>x.AllocatedWeight)))throw new BusinessRuleException("Completion weight totals are invalid.");
  if(r.TotalConsumedWeight<0||r.TotalScrapWeight<0)throw new BusinessRuleException("Completion weight totals cannot be negative.");
  if(active.Length==0&&r.TotalJobWeight<=0)throw new BusinessRuleException("Total Job Weight is required when material allocation was skipped.");
  var now=DateTimeOffset.UtcNow;var actor=Actor();
  foreach(var a in active){var item=r.Allocations.Single(x=>x.AllocationId==a.Id);if(item.ActualConsumedWeight<0||item.ActualConsumedWeight>a.AllocatedWeight)throw new BusinessRuleException($"Consumption for {a.SlitCoilNumber} exceeds its allocation.");var coil=await db.SlitCoils.SingleOrDefaultAsync(x=>x.Id==a.SlitCoilId,t)??throw new BusinessRuleException($"Slit Coil {a.SlitCoilNumber} no longer exists.");coil.ConsumeForLamination(item.ActualConsumedWeight);a.RecordConsumption(item.ActualConsumedWeight,actor,now,item.Remarks);var inv=new InventoryTransaction(InventoryTransactionType.LaminationConsumption,CoilType.SlitCoil,coil.Id,coil.CoilNumber,j.Id,j.LaminationJobNumber,CoilStatus.Available,coil.Status,item.ActualConsumedWeight,now,$"Consumed for Lamination Job; unused reservation {a.AllocatedWeight-item.ActualConsumedWeight:N3} kg released.");inv.SetCreatedAudit(actor,now);db.InventoryTransactions.Add(inv);}
  foreach(var item in manual){if(item.ActualConsumedWeight<=0)throw new BusinessRuleException("Manual consumed weight must be greater than zero.");var coil=await db.SlitCoils.SingleOrDefaultAsync(x=>x.Id==item.SlitCoilId,t)??throw new BusinessRuleException("A selected Slit Coil no longer exists.");if(coil.Status!=CoilStatus.Available||coil.GradeId!=j.GradeId||coil.Thickness!=j.Thickness||!Requirements(j).Any(x=>Math.Abs(x.Width-coil.Width)<=WidthTolerance))throw new BusinessRuleException($"Slit Coil {coil.CoilNumber} must be available and match the job Grade, Thickness, and a required Width.");decimal reserved=await db.LaminationJobMaterialAllocations.Where(x=>x.SlitCoilId==coil.Id&&x.Status==AllocationStatus.Reserved).SumAsync(x=>(decimal?)x.AllocatedWeight,t)??0;decimal available=coil.Weight-reserved;if(item.ActualConsumedWeight>available)throw new BusinessRuleException($"Consumption for {coil.CoilNumber} exceeds available weight of {available:N3} kg.");var before=coil.Status;coil.ConsumeForLamination(item.ActualConsumedWeight);var allocation=new LaminationJobMaterialAllocation(j.Id,coil.Id,coil.CoilNumber,coil.Width,item.ActualConsumedWeight,available-item.ActualConsumedWeight,actor,now,$"MANUAL ISSUE: {item.Remarks}");allocation.RecordConsumption(item.ActualConsumedWeight,actor,now,item.Remarks);j.Allocations.Add(allocation);db.Entry(allocation).State=EntityState.Added;var inv=new InventoryTransaction(InventoryTransactionType.LaminationConsumption,CoilType.SlitCoil,coil.Id,coil.CoilNumber,j.Id,j.LaminationJobNumber,before,coil.Status,item.ActualConsumedWeight,now,"Manual material issue recorded during Lamination completion.");inv.SetCreatedAudit(actor,now);db.InventoryTransactions.Add(inv);}  j.Complete(r.TotalGoodPieces,r.TotalRejectedPieces,r.TotalConsumedWeight,r.TotalScrapWeight,r.TotalJobWeight,r.CompletionRemarks,actor,now);j.Recalculate();await db.SaveChangesAsync(t);await tx.CommitAsync(t);return Map(j);
 }
 public async Task<LaminationCompletionDto> CompletionAsync(Guid id,CancellationToken t=default){var j=await Find(id,t);if(j.Status!=LaminationJobStatus.Completed)throw new BusinessRuleException("Completion is available only for a Completed job.");return new(j.Id,j.LaminationJobNumber,j.TotalGoodPieces,j.TotalRejectedPieces,j.TotalConsumedWeight,j.TotalScrapWeight,j.TotalJobWeight,j.CompletedBy,j.CompletedOn,j.CompletionRemarks,j.Allocations.Select(x=>MapAllocation(x)).ToArray());}
 public async Task<LaminationJobDetailsDto> CancelAsync(Guid id,CancellationToken t=default) { var j=await Find(id,t); foreach(var a in j.Allocations.Where(x=>x.Status==AllocationStatus.Reserved))a.Release(Actor(),DateTimeOffset.UtcNow); j.Cancel(Actor(),DateTimeOffset.UtcNow); j.Recalculate(); await db.SaveChangesAsync(t); return Map(j); }
 public async Task<LaminationMetricsDto> MetricsAsync(CancellationToken t=default) { var jobs=await Jobs(true).ToListAsync(t); var queue=jobs.Where(x=>x.Status is LaminationJobStatus.Draft or LaminationJobStatus.Allocated or LaminationJobStatus.Released).OrderBy(x=>x.PlannedDate).Select(x=>new LaminationQueueItemDto(x.Id,x.LaminationJobNumber,x.JobOrDrawingNumber,x.Rating,x.Status,x.TotalPlannedWeight<=0?0:Math.Min(100,100*x.TotalAllocatedWeight/x.TotalPlannedWeight),x.PlannedDate,x.Machine,x.Shift)).ToArray(); return new(jobs.Count(x=>x.Status==LaminationJobStatus.Draft),jobs.Count(x=>x.Status==LaminationJobStatus.Released),jobs.Count(x=>x.Status==LaminationJobStatus.Allocated),jobs.Count(x=>x.Status==LaminationJobStatus.Completed&&x.CompletedOn.HasValue&&x.CompletedOn.Value.UtcDateTime.Date==DateTime.UtcNow.Date),jobs.Count(x=>x.Status==LaminationJobStatus.Released&&Requirements(x).Any(r=>r.ShortageWeight>0)),jobs.Count(x=>x.Status==LaminationJobStatus.Cancelled),queue); }
 async Task<Grade> SuitableGrade(Guid id,string requestedCategory,decimal requestedLoss,CancellationToken t) { var grade=await db.Grades.SingleOrDefaultAsync(x=>x.Id==id&&x.IsActive,t)??throw new BusinessRuleException("An active Grade is required."); if(string.IsNullOrWhiteSpace(requestedCategory))throw new BusinessRuleException("Customer Category is required."); if(!grade.Category.Equals(requestedCategory.Trim(),StringComparison.OrdinalIgnoreCase))throw new BusinessRuleException($"Selected grade is {grade.Category}; customer category {requestedCategory} is required."); if(requestedLoss<=0)throw new BusinessRuleException("Customer Core Loss (W/kg) must be greater than zero."); if(grade.CoreLossPerKg>requestedLoss)throw new BusinessRuleException($"Selected {grade.Category} grade has a core loss of {grade.CoreLossPerKg} W/kg and does not meet the customer limit of {requestedLoss} W/kg."); return grade; }
 async Task<LaminationJob> Find(Guid id,CancellationToken t)=>await Jobs(true).SingleOrDefaultAsync(x=>x.Id==id,t)??throw new NotFoundException("Lamination Job was not found.");
 static LaminationJobStep Build(LaminationJobStepDto s) { var x=new LaminationJobStep(s.StepNumber,s.StackQuantity,s.Sequence,s.Width,s.PlannedWeight,s.Remarks); foreach(var p in s.Plates){var plate=new LaminationJobPlate(p.PlateType,p.Width,p.Length,p.Quantity,p.PlannedWeight,p.Remarks);foreach(var d in p.Dimensions)plate.AddDimension(new(d.DimensionCode,d.DisplayName,d.DimensionValue,d.Unit,d.Sequence,d.Remarks));x.AddPlate(plate);}return x; }
 static IReadOnlyList<LaminationMaterialRequirementDto> Requirements(LaminationJob j)=>j.Steps.SelectMany(s=>s.Plates.Select(p=>new{s,p})).GroupBy(x=>x.p.Width).Select(g=>{decimal required=g.Sum(x=>x.p.PlannedWeight);decimal allocated=j.Allocations.Where(a=>a.Status==AllocationStatus.Reserved&&Math.Abs(a.RequiredWidth-g.Key)<=WidthTolerance).Sum(a=>a.AllocatedWeight);return new LaminationMaterialRequirementDto(g.Key,required,allocated,Math.Max(0,required-allocated),j.Grade?.Code??"",j.Thickness,g.Select(x=>x.s.StepNumber).Distinct().Order().ToArray(),g.Select(x=>x.p.PlateType).Distinct().ToArray());}).OrderBy(x=>x.Width).ToArray();
 static LaminationJobListItemDto List(LaminationJob x)=>new(x.Id,x.LaminationJobNumber,x.JobOrDrawingNumber,x.Customer,x.Rating,x.DesignType,x.NumberOfSteps,x.Grade?.Code??"",x.TotalWeight,x.TotalPlannedWeight,x.TotalAllocatedWeight,x.Status,x.PlannedDate,x.CreatedAtUtc);
 static LaminationJobMaterialAllocationDto MapAllocation(LaminationJobMaterialAllocation a,decimal coreLossPerKg=0)=>new(a.Id,a.SlitCoilId,a.SlitCoilNumber,a.RequiredWidth,a.AllocatedWeight,a.IssuedWeight,a.ConsumedWeight,a.RemainingWeightAfterAllocation,a.Status,a.ReservedBy,a.ReservedOn,a.ReleasedBy,a.ReleasedOn,a.Remarks,coreLossPerKg);
 static LaminationJobDetailsDto Map(LaminationJob x)=>new(x.Id,x.LaminationJobNumber,x.JobOrDrawingNumber,x.Customer,x.Rating,x.DesignType,x.StepLapOrientation,x.NumberOfSteps,x.GradeId,x.Grade?.Code??"",x.Thickness,x.Category,x.CoreLossPerKg,x.TotalWeight,x.CustomerCoreLossPerKg,x.NoLoadLossWatts,x.WorkOrderId,x.WorkOrderNumber,x.PlannedDate,x.RequiredDate,x.Machine,x.Shift,x.PlannerName,x.Status,x.TotalPlannedPieces,x.TotalPlannedWeight,x.TotalAllocatedWeight,x.Remarks,x.DrawingAttachmentName,x.ReleasedBy,x.ReleasedOn,x.AllocatedBy,x.AllocatedOn,x.CancelledBy,x.CancelledOn,x.CreatedAtUtc,x.UpdatedAtUtc,Convert.ToBase64String(x.RowVersion),x.Steps.OrderBy(s=>s.Sequence).Select(s=>new LaminationJobStepDto(s.Id,s.StepNumber,s.StackQuantity,s.Sequence,s.Width,s.PlannedWeight,s.Remarks,s.Plates.Select(p=>new LaminationJobPlateDto(p.Id,p.PlateType,p.Width,p.Length,p.Quantity,p.PlannedWeight,p.Remarks,p.Dimensions.OrderBy(d=>d.Sequence).Select(d=>new LaminationPlateDimensionDto(d.Id,d.DimensionCode,d.DisplayName,d.DimensionValue,d.Unit,d.Sequence,d.Remarks)).ToArray())).ToArray())).ToArray());
 string Actor()=>string.IsNullOrWhiteSpace(user.UserName)?user.UserId??"System":user.UserName;
}
