using CoilManager.Domain.Enums;

namespace CoilManager.Application.DTOs.RawCoils;

public sealed record RawCoilDto(
    Guid Id,
    string RawCoilNumber,
    string CoilID,
    string CoilNumber,
    string HeatNumber,
    string? PONumber,
    string? InvoiceNo,
    string? MillTCNo,
    string? BISLicNumber,
    Guid SupplierId,
    string SupplierName,
    Guid ManufacturerId,
    string ManufacturerName,
    Guid GradeId,
    string Grade,
    decimal Thickness,
    decimal Width,
    decimal Weight,
    decimal Length,
    decimal WattLossPerKg,
    string? WarehouseLocation,
    CoilStatus Status,
    DateOnly ReceivedDate,
    DateTimeOffset CreatedOn,
    string? CreatedBy,
    DateTimeOffset? ModifiedOn,
    string? ModifiedBy,
    bool IsDeleted,
    DateTimeOffset? DeletedOn,
    string RowVersion,
    IReadOnlyList<string> DocumentPlaceholders);
