import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { LaminationJobService } from './lamination-job.service';
import { LaminationJob } from './lamination-job.model';

@Component({selector:'app-complete-lamination-job',standalone:true,imports:[CommonModule,FormsModule,RouterLink,MatButtonModule,MatFormFieldModule,MatInputModule,MatSnackBarModule],template:`
<header><div><h1>Complete Lamination Job</h1><p>Record actual Slit Coil consumption and production results.</p></div><a mat-button [routerLink]="['/lamination-jobs',id]">Back to Details</a></header>
@if(job();as j){<section class="card"><h2>{{j.laminationJobNumber}}</h2><p>{{j.jobOrDrawingNumber}} · {{j.rating}} · {{j.grade}} · {{j.status}}</p></section>
<section class="card"><h2>Allocated Slit Coils</h2><div class="head"><b>Slit Coil</b><b>Allocated</b><b>Actual Consumed</b><b>Unused</b><b>Remarks</b></div>@for(a of allocations();track a.id){<div class="row"><span>{{a.slitCoilNumber}}</span><span>{{a.allocatedWeight|number:'1.2-2'}} kg</span><input type="number" min="0" [max]="a.allocatedWeight" [(ngModel)]="a.actualConsumedWeight"><span>{{a.allocatedWeight-(a.actualConsumedWeight||0)|number:'1.2-2'}} kg</span><input [(ngModel)]="a.completionRemarks" placeholder="Remarks"></div>}</section>
<section class="card"><h2>Plate Production Results</h2><div class="head plates"><b>Step / Plate</b><b>Planned</b><b>Good</b><b>Rejected</b><b>Actual Weight</b></div>@for(p of plateResults();track p.key){<div class="row plates"><span>Step {{p.stepNumber}} · {{plateName(p.plateType)}}</span><span>{{p.plannedQuantity}}</span><input type="number" min="0" [(ngModel)]="p.goodQuantity"><input type="number" min="0" [(ngModel)]="p.rejectedQuantity"><input type="number" min="0" [(ngModel)]="p.actualWeight"></div>}</section>
<section class="card summary"><h2>Completion Summary</h2><mat-form-field appearance="outline"><mat-label>Scrap Weight (kg)</mat-label><input matInput type="number" min="0" [(ngModel)]="scrapWeight"></mat-form-field><mat-form-field appearance="outline"><mat-label>Completion Remarks</mat-label><textarea matInput [(ngModel)]="remarks"></textarea></mat-form-field></section>
<footer><a mat-stroked-button [routerLink]="['/lamination-jobs',id]">Cancel</a><button mat-flat-button color="primary" (click)="complete()">Complete Lamination Job</button></footer>}
`,styles:[`header,footer,.head,.row{display:flex;align-items:center;justify-content:space-between;gap:16px}.card{background:#fff;border:1px solid #dce3ea;border-radius:10px;padding:18px;margin:16px 0}.head,.row{display:grid;grid-template-columns:1.3fr repeat(3,1fr) 1.5fr;padding:10px}.head{background:#eef3f8}.row{border-bottom:1px solid #e5e7eb}.plates{grid-template-columns:2fr repeat(4,1fr)}input{min-width:0;padding:10px;border:1px solid #cbd5e1;border-radius:5px}.summary{display:grid;grid-template-columns:1fr 2fr;gap:16px}footer{justify-content:flex-end;position:sticky;bottom:0;background:#fff;padding:14px}@media(max-width:800px){.card{overflow:auto}.head,.row{min-width:760px}header{align-items:flex-start}}`]})
export class CompleteLaminationJobComponent{
 private api=inject(LaminationJobService);private router=inject(Router);private snack=inject(MatSnackBar);private route=inject(ActivatedRoute);id=this.route.snapshot.paramMap.get('id')!;job=signal<LaminationJob|null>(null);allocations=signal<any[]>([]);plateResults=signal<any[]>([]);scrapWeight=0;remarks='';
 constructor(){this.api.get(this.id).subscribe(r=>{const j=r.data;this.job.set(j);if(!this.isAllocated(j.status)){this.snack.open('Only an Allocated job can be completed.','Close',{duration:5000});this.router.navigate(['/lamination-jobs',this.id]);return}this.plateResults.set(j.steps.flatMap(s=>s.plates.map(p=>({key:`${s.id}-${p.plateType}`,stepId:s.id,stepNumber:s.stepNumber,plateType:p.plateType,plannedQuantity:p.quantity,goodQuantity:p.quantity,rejectedQuantity:0,actualWeight:null,remarks:null}))));});this.api.allocations(this.id).subscribe(r=>this.allocations.set(r.data.filter((a:any)=>a.status==='Reserved'||a.status===0).map((a:any)=>({...a,actualConsumedWeight:a.allocatedWeight,completionRemarks:null}))));}
 plateName(v:any){return typeof v==='number'?['Side','Center','Top','Bottom'][v]:v}private isAllocated(v:any){return v===1||v==='Allocated'}
 complete(){const allocations=this.allocations();const plates=this.plateResults();const consumed=allocations.reduce((n,a)=>n+(+a.actualConsumedWeight||0),0);const body={rowVersion:this.job()!.rowVersion,allocations:allocations.map(a=>({allocationId:a.id,actualConsumedWeight:+a.actualConsumedWeight||0,remarks:a.completionRemarks})),plateResults:plates.map(({key,stepNumber,...p})=>p),totalGoodPieces:plates.reduce((n,p)=>n+(+p.goodQuantity||0),0),totalRejectedPieces:plates.reduce((n,p)=>n+(+p.rejectedQuantity||0),0),totalConsumedWeight:consumed,totalScrapWeight:+this.scrapWeight||0,completionRemarks:this.remarks};this.api.complete(this.id,body).subscribe({next:()=>{this.snack.open('Lamination Job completed successfully.','Close',{duration:4000});this.router.navigate(['/lamination-jobs',this.id])},error:e=>this.snack.open(e.error?.message||e.error?.errors?.join(' | ')||'Completion failed.','Close',{duration:6000})});}
}