import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatSelectModule } from '@angular/material/select';
import { finalize, forkJoin } from 'rxjs';
import { LaminationJob } from './lamination-job.model';
import { LaminationJobService } from './lamination-job.service';
@Component({selector:'app-complete-lamination-job',standalone:true,imports:[CommonModule,FormsModule,RouterLink,MatButtonModule,MatCardModule,MatIconModule,MatInputModule,MatProgressBarModule,MatSnackBarModule,MatSelectModule],templateUrl:'./complete-lamination-job.component.html',styleUrl:'./complete-lamination-job.component.scss'})
export class CompleteLaminationJobComponent{
 private api=inject(LaminationJobService);private router=inject(Router);private snack=inject(MatSnackBar);private route=inject(ActivatedRoute);readonly id=this.route.snapshot.paramMap.get('id')!;readonly job=signal<LaminationJob|null>(null);readonly allocations=signal<any[]>([]);readonly manualCandidates=signal<any[]>([]);readonly manualAllocations=signal<any[]>([{key:1,slitCoilId:'',actualConsumedWeight:0,remarks:''}]);readonly plateResults=signal<any[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly totalJobWeight=signal<number|null>(null);scrapWeight=0;remarks='';private nextManualKey=2;
 readonly allocatedWeight=computed(()=>this.allocations().reduce((n,a)=>n+(+a.allocatedWeight||0),0));readonly consumedWeight=computed(()=>this.allocations().length?this.allocations().reduce((n,a)=>n+(+a.actualConsumedWeight||0),0):this.manualAllocations().reduce((n,a)=>n+(+a.actualConsumedWeight||0),0));readonly unusedWeight=computed(()=>this.allocatedWeight()-this.consumedWeight());readonly goodPieces=computed(()=>this.plateResults().reduce((n,p)=>n+(+p.goodQuantity||0),0));readonly rejectedPieces=computed(()=>this.plateResults().reduce((n,p)=>n+(+p.rejectedQuantity||0),0));readonly canComplete=computed(()=>!this.saving()&&(this.allocations().length>0||+(this.totalJobWeight()??0)>0)&&this.manualAllocations().filter(a=>!!a.slitCoilId).every(a=>+a.actualConsumedWeight>0&&+a.actualConsumedWeight<=this.manualAvailable(a))&&this.allocations().every(a=>+a.actualConsumedWeight>=0&&+a.actualConsumedWeight<=+a.allocatedWeight)&&this.plateResults().every(p=>+p.goodQuantity>=0&&+p.rejectedQuantity>=0&&(+p.goodQuantity)+(+p.rejectedQuantity)<=+p.plannedQuantity)&&+(this.totalJobWeight()??0)>=0&&this.scrapWeight>=0);
 constructor(){this.api.get(this.id).subscribe({next:r=>{const j=r.data;this.job.set(j);this.loadApplicableCoils(j);if(!this.isAllocated(j.status)){this.snack.open('Only an Allocated job can be completed.','Close',{duration:5000});this.router.navigate(['/lamination-jobs']);return}this.plateResults.set(j.steps.flatMap(s=>s.plates.map(p=>({key:`${s.id}-${p.plateType}`,stepId:s.id,stepNumber:s.stepNumber,plateType:p.plateType,plannedQuantity:this.productionQuantity(s.stackQuantity,p.plateType),plannedWidth:p.width,plannedLength:p.length,goodQuantity:this.productionQuantity(s.stackQuantity,p.plateType),rejectedQuantity:0,remarks:null}))));},error:e=>this.error(e,'Unable to load Lamination Job.')});this.api.allocations(this.id).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>this.allocations.set(r.data.filter((a:any)=>a.status==='Reserved'||a.status===0).map((a:any)=>({...a,actualConsumedWeight:a.allocatedWeight,completionRemarks:null}))),error:e=>this.error(e,'Unable to load allocations.')});}
 loadApplicableCoils(j:LaminationJob){const widths=[...new Set(j.steps.flatMap(s=>s.plates.map(p=>+p.width)))];if(!widths.length){this.manualCandidates.set([]);return}forkJoin(widths.map(width=>this.api.available(this.id,{width,grade:j.grade,thickness:j.thickness}))).subscribe({next:responses=>{const unique=new Map<string,any>();responses.flatMap(x=>x.data).forEach(coil=>unique.set(coil.id,coil));this.manualCandidates.set([...unique.values()])},error:()=>this.manualCandidates.set([])})} addManualCoil(){this.manualAllocations.update(rows=>[...rows,{key:this.nextManualKey++,slitCoilId:'',actualConsumedWeight:0,remarks:''}])}
 removeManualCoil(key:number){this.manualAllocations.update(rows=>rows.filter(x=>x.key!==key))}
 manualCoil(row:any){return this.manualCandidates().find(c=>c.id===row.slitCoilId)}
 manualCoilSelectedByOther(coilId:string,key:number){return this.manualAllocations().some(x=>x.key!==key&&x.slitCoilId===coilId)}
 manualAvailable(row:any){return +(this.manualCoil(row)?.availableWeight||0)} plateName(v:any){return typeof v==='number'?['Side','Center','Top','Bottom'][v]:v}productionPlateName(v:any){return this.plateName(v)==='Side'?'Left + Right Side':String(this.plateName(v))}productionQuantity(stackQuantity:number,plateType:any){return this.plateName(plateType)==='Side'?(+stackQuantity||0)*2:(+stackQuantity||0)}
resultsForStep(stepId:string){return this.plateResults().filter(p=>p.stepId===stepId)}stepGood(stepId:string){return this.resultsForStep(stepId).reduce((n,p)=>n+(+p.goodQuantity||0),0)}stepRejected(stepId:string){return this.resultsForStep(stepId).reduce((n,p)=>n+(+p.rejectedQuantity||0),0)}remaining(a:any){return Math.max(0,(+a.allocatedWeight||0)-(+a.actualConsumedWeight||0))}remainingPhysical(a:any){return Math.max(0,(+a.currentWeight||+a.allocatedWeight||0)-(+a.actualConsumedWeight||0))}rowValid(a:any){return +a.actualConsumedWeight>=0&&+a.actualConsumedWeight<=+a.allocatedWeight}private isAllocated(v:any){return v===1||v==='Allocated'}
 complete(){if(!this.canComplete()){this.snack.open('Correct the highlighted production values before completing.','Close',{duration:5000});return}const allocations=this.allocations(),plates=this.plateResults();const body={rowVersion:this.job()!.rowVersion,allocations:allocations.map(a=>({allocationId:a.id,actualConsumedWeight:+a.actualConsumedWeight||0,remarks:a.completionRemarks})),plateResults:plates.map(({key,stepNumber,...p})=>p),totalGoodPieces:this.goodPieces(),totalRejectedPieces:this.rejectedPieces(),totalConsumedWeight:this.consumedWeight(),manualAllocations:this.allocations().length?[]:this.manualAllocations().filter(a=>!!a.slitCoilId).map(a=>({slitCoilId:a.slitCoilId,actualConsumedWeight:+a.actualConsumedWeight||0,remarks:a.remarks})),totalJobWeight:+(this.totalJobWeight()??0),totalScrapWeight:+this.scrapWeight||0,completionRemarks:this.remarks};this.saving.set(true);this.api.complete(this.id,body).pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>{this.snack.open('Lamination Job completed successfully.','Close',{duration:4000});this.router.navigate(['/lamination-jobs'])},error:e=>this.error(e,'Completion failed.')});}
 private error(e:any,fallback:string){this.snack.open(e?.error?.message||e?.error?.errors?.join(' | ')||fallback,'Close',{duration:6000})}
}