import { CommonModule, DOCUMENT } from '@angular/common';
import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { finalize } from 'rxjs';
import { LaminationJob, Plate, PlateType, Step } from './lamination-job.model';
import { LaminationJobService } from './lamination-job.service';
@Component({selector:'app-lamination-job-card',standalone:true,imports:[CommonModule,RouterLink,MatButtonModule,MatCardModule,MatIconModule,MatProgressBarModule,MatSnackBarModule],templateUrl:'./lamination-job-card.component.html',styleUrl:'./lamination-job-card.component.scss'})
export class LaminationJobCardComponent implements OnInit,OnDestroy{
 protected job=signal<LaminationJob|null>(null);protected allocations=signal<any[]>([]);protected manualAllocation=false;protected loading=signal(false);protected error=signal('');private document=inject(DOCUMENT);private route=inject(ActivatedRoute);private api=inject(LaminationJobService);private snack=inject(MatSnackBar);
 ngOnInit(){this.document.body.classList.add('job-card-print-mode');this.manualAllocation=this.route.snapshot.queryParamMap.get('manualAllocation')==='true';const id=this.route.snapshot.paramMap.get('id');if(!id){this.error.set('Lamination Job id is required.');return}this.loading.set(true);this.api.get(id).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{if(![1,2,4].includes(this.statusValue(r.data.status))){this.error.set('Job Card is available only after the Lamination Job is released.');return}this.job.set(r.data);this.api.allocations(id).subscribe({next:a=>this.allocations.set(a.data||[]),error:()=>this.allocations.set([])})},error:e=>this.showError(e)})}
 ngOnDestroy(){this.document.body.classList.remove('job-card-print-mode')}protected print(){window.print()}protected statusValue(v:unknown){return typeof v==='number'?v:['Draft','Allocated','Released','InProgress','Completed','Cancelled'].indexOf(`${v}`)}protected statusName(v:unknown){return ['Draft','In Progress','Released','Legacy In Progress','Completed','Cancelled'][this.statusValue(v)]??`${v}`}protected designName(v:unknown){return v===1||v==='StepLap'?'Step-Lap':'Simple'}protected plateName(v:PlateType|number){return typeof v==='number'?['Side','Center','Top','Bottom'][v]:v}protected plate(step:Step,type:PlateType):Plate|undefined{return step.plates.find(p=>this.plateName(p.plateType)===type)}protected plateWeight(step:Step,...types:PlateType[]):number{return types.reduce((sum,type)=>sum+(this.plate(step,type)?.plannedWeight||0),0)}protected totalStack(j:LaminationJob){return j.steps.reduce((n,s)=>n+s.stackQuantity,0)}protected plannedPieces(j:LaminationJob){return this.totalStack(j)*5}private showError(e:any){const m=e?.error?.errors?.join(' | ')||e?.error?.message||'Unable to load Lamination Job Card.';this.error.set(m);this.snack.open(m,'Close',{duration:6000})}
}