import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { LaminationJobService } from './lamination-job.service';
import { LaminationJob } from './lamination-job.model';

@Component({
  selector:'app-lamination-detail', imports:[CommonModule,RouterLink,MatButtonModule],
  template:`<ng-container *ngIf="job() as j"><header><div><p>Lamination Job</p><h1>{{j.laminationJobNumber}}</h1><span class="status">{{statusName(j.status)}}</span></div><div><a mat-stroked-button *ngIf="statusValue(j.status)===0" [routerLink]="['/lamination-jobs',j.id,'edit']">Edit Job</a> <button mat-flat-button color="primary" *ngIf="statusValue(j.status)===0" (click)="release()">Release Job</button> <a mat-flat-button color="primary" *ngIf="statusValue(j.status)===2" [routerLink]="['/lamination-jobs',j.id,'allocations']">Allocate Material</a> <a mat-flat-button color="primary" *ngIf="statusValue(j.status)===1" [routerLink]="['/lamination-jobs',j.id,'complete']">Complete Lamination Job</a> <a mat-stroked-button *ngIf="statusValue(j.status)===1 || statusValue(j.status)===2 || statusValue(j.status)===4" [routerLink]="['/lamination-jobs',j.id,'job-card']">{{statusValue(j.status)===4?'Reprint':'Print'}} Job Card</a></div></header><p class="locked" *ngIf="statusValue(j.status)!==0 && statusValue(j.status)!==4 && statusValue(j.status)!==5">The cutting schedule is released and locked. Complete material allocation to proceed.</p><section class="grid"><article><h2>Job Information</h2><dl><dt>Job No / Drawing No</dt><dd>{{j.jobOrDrawingNumber||'—'}}</dd><dt>Rating</dt><dd>{{j.rating}}</dd><dt>Customer</dt><dd>{{j.customer||'—'}}</dd><dt>Machine</dt><dd>{{j.machine}}</dd><dt>Planned Date</dt><dd>{{j.plannedDate|date}}</dd></dl></article><article><h2>Material & Design</h2><dl><dt>Grade</dt><dd>{{j.grade}}</dd><dt>Thickness</dt><dd>{{j.thickness}} mm</dd><dt>Category</dt><dd>{{j.category}}</dd><dt>Core Loss</dt><dd>{{j.customerCoreLossPerKg}} W/kg</dd><dt>Design</dt><dd>{{designName(j.designType)}} · {{orientationName(j.stepLapOrientation)}} · {{j.numberOfSteps}} steps</dd></dl></article><article><h2>Customer Loss Summary</h2><dl><dt>Total Weight</dt><dd>{{j.totalWeight|number:'1.2-2'}} kg</dd><dt>No Load Loss</dt><dd>{{j.noLoadLossWatts|number:'1.2-2'}} W</dd><dt>Planned Weight</dt><dd>{{j.totalPlannedWeight|number:'1.2-2'}} kg</dd><dt>Allocated Weight</dt><dd>{{j.totalAllocatedWeight|number:'1.2-2'}} kg</dd></dl></article></section><section class="schedule"><h2>Step Schedule</h2><article *ngFor="let s of j.steps"><h3>Step {{s.stepNumber}} — Stack {{s.stackQuantity}}</h3><table><tr><th>Plate Type</th><th>Width</th><th>Length</th><th>Quantity</th><th>Weight</th></tr><tr *ngFor="let p of s.plates"><td>{{plateTypeName(p.plateType)}}</td><td>{{p.width}} mm</td><td>{{p.length||'OEM dimensions'}}</td><td>{{p.quantity}}</td><td>{{p.plannedWeight}} kg</td></tr></table></article></section></ng-container>`,
  styles:[`header{display:flex;justify-content:space-between;align-items:center}.locked{padding:12px;background:#fff7ed;border:1px solid #fed7aa;border-radius:8px}.status{background:#dbeafe;border-radius:16px;padding:6px 12px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:20px 0}article,.schedule{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:18px}dl{display:grid;grid-template-columns:1fr 1fr;gap:10px}dt{color:#64748b}dd{margin:0;font-weight:600}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #e2e8f0;text-align:left}@media(max-width:800px){.grid{grid-template-columns:1fr}}`]
})
export class LaminationDetailComponent {
  statusValue(value:unknown):number{return typeof value==='number'?value:['Draft','Allocated','Released','InProgress','Completed','Cancelled'].indexOf(`${value}`)}
  statusName(value:unknown):string{return ['Draft','Allocated','Released','In Progress','Completed','Cancelled'][this.statusValue(value)]??'Unknown'}
  designName(value:unknown):string{return value===1||value==='StepLap'?'Step Lap':'Simple'}
  orientationName(value:unknown):string{return typeof value==='number'?['Not Applicable','Horizontal','Vertical','Horizontal & Vertical'][value]??'Unknown':`${value}`.replace('HorizontalAndVertical','Horizontal & Vertical').replace('NotApplicable','Not Applicable')}
  plateTypeName(value:unknown):string{return typeof value==='number'?['Side','Center','Top','Bottom'][value]??'Unknown':`${value}`}
  private api=inject(LaminationJobService); id=inject(ActivatedRoute).snapshot.paramMap.get('id')!; job=signal<LaminationJob|null>(null);
  constructor(){this.load();} load(){this.api.get(this.id).subscribe(x=>this.job.set(x.data));} release(){this.api.release(this.id).subscribe(x=>this.job.set(x.data));}
}
