using CoilManager.Domain.Common;
using CoilManager.Domain.Enums;

namespace CoilManager.Domain.Entities;

public sealed class Dispatch : AuditableEntity
{
    private readonly List<DispatchPackage> _packages = [];
    private readonly List<DispatchInventorySource> _inventorySources = [];
    private Dispatch() { }
    public Dispatch(string number,string packingSlip,WorkOrder wo,decimal quantity,DateOnly? date,string shippingAddress,string? contact,string? phone,string? remarks)
    {
        DispatchNumber=Required(number);PackingSlipNumber=Required(packingSlip);WorkOrderId=wo.Id;WorkOrderNumber=wo.WorkOrderNumber;
        SalesOrderId=wo.SalesOrderId;SalesOrderNumber=wo.SalesOrderNumber;SalesOrderLineId=wo.SalesOrderLineId;CustomerId=wo.CustomerId;
        CustomerCode=wo.CustomerCode;CustomerName=wo.CustomerName??"Inventory Customer";CustomerPONumber=wo.CustomerPONumber;
        ProductType=wo.ProductType;Description=wo.Description;GradeCode=wo.GradeCode??wo.Grade?.Code;Thickness=wo.Thickness;Width=wo.RequiredWidth;
        DrawingNumber=wo.DrawingNumber;DrawingRevision=wo.DrawingRevision;OEMJobNumber=wo.OEMJobNumber;TransformerRating=wo.TransformerRating;
        Category=wo.Category;CoreLossPerKg=wo.CoreLossPerKg;DispatchQuantity=quantity;QuantityUnit=wo.QuantityUnit;DispatchDate=date;
        ShippingAddress=Required(shippingAddress);ContactPerson=Optional(contact);ContactPhone=Optional(phone);DispatchRemarks=Optional(remarks);Status=DispatchStatus.Draft;
    }
    public string DispatchNumber{get;private set;}="";public string PackingSlipNumber{get;private set;}="";public Guid WorkOrderId{get;private set;}public WorkOrder? WorkOrder{get;private set;}public string WorkOrderNumber{get;private set;}="";
    public Guid? SalesOrderId{get;private set;}public string? SalesOrderNumber{get;private set;}public Guid? SalesOrderLineId{get;private set;}public Guid? CustomerId{get;private set;}public string? CustomerCode{get;private set;}public string CustomerName{get;private set;}="";public string? CustomerPONumber{get;private set;}
    public WorkOrderProductType ProductType{get;private set;}public string Description{get;private set;}="";public string? GradeCode{get;private set;}public decimal? Thickness{get;private set;}public decimal? Width{get;private set;}public string? DrawingNumber{get;private set;}public string? DrawingRevision{get;private set;}public string? OEMJobNumber{get;private set;}public string? TransformerRating{get;private set;}public string? Category{get;private set;}public decimal? CoreLossPerKg{get;private set;}
    public decimal DispatchQuantity{get;private set;}public QuantityUnit QuantityUnit{get;private set;}public decimal? NetWeight{get;private set;}public decimal? GrossWeight{get;private set;}public int? NumberOfPackages{get;private set;}public DateOnly? DispatchDate{get;private set;}
    public string? TransporterName{get;private set;}public string? VehicleNumber{get;private set;}public string? LRGRNumber{get;private set;}public DateOnly? LRGRDate{get;private set;}public string? EWayBillNumber{get;private set;}public DateOnly? EWayBillDate{get;private set;}public string ShippingAddress{get;private set;}="";public string? ContactPerson{get;private set;}public string? ContactPhone{get;private set;}public string? PackingRemarks{get;private set;}public string? DispatchRemarks{get;private set;}
    public DispatchStatus Status{get;private set;}public string? DispatchedBy{get;private set;}public DateTimeOffset? DispatchedOn{get;private set;}public string? CancelledBy{get;private set;}public DateTimeOffset? CancelledOn{get;private set;}public string? CancellationReason{get;private set;}public byte[] RowVersion{get;private set;}=[];
    public IReadOnlyCollection<DispatchPackage> Packages=>_packages;public IReadOnlyCollection<DispatchInventorySource> InventorySources=>_inventorySources;
    public void Update(decimal quantity,DateOnly? date,string shippingAddress,string? contact,string? phone,decimal? net,decimal? gross,string? transporter,string? vehicle,string? lrgr,DateOnly? lrgrDate,string? eway,DateOnly? ewayDate,string? packingRemarks,string? dispatchRemarks,IEnumerable<DispatchPackage> packages)
    {if(Status!=DispatchStatus.Draft)throw new InvalidOperationException("Only Draft Dispatches can be edited.");DispatchQuantity=quantity;DispatchDate=date;ShippingAddress=Required(shippingAddress);ContactPerson=Optional(contact);ContactPhone=Optional(phone);NetWeight=net;GrossWeight=gross;TransporterName=Optional(transporter);VehicleNumber=Optional(vehicle);LRGRNumber=Optional(lrgr);LRGRDate=lrgrDate;EWayBillNumber=Optional(eway);EWayBillDate=ewayDate;PackingRemarks=Optional(packingRemarks);DispatchRemarks=Optional(dispatchRemarks);_packages.Clear();_packages.AddRange(packages);NumberOfPackages=_packages.Count;}
    public void Confirm(string actor,DateTimeOffset at,IEnumerable<DispatchInventorySource> sources){if(Status!=DispatchStatus.Draft)throw new InvalidOperationException("Only a Draft Dispatch can be confirmed.");Status=DispatchStatus.Dispatched;DispatchedBy=actor;DispatchedOn=at;DispatchDate??=DateOnly.FromDateTime(at.UtcDateTime);_inventorySources.AddRange(sources);}
    public void SelectCustomer(Customer customer){if(Status!=DispatchStatus.Draft)throw new InvalidOperationException("Only a Draft Dispatch can be edited.");CustomerId=customer.Id;CustomerCode=customer.CustomerCode;CustomerName=customer.CustomerName;ShippingAddress=customer.ShippingAddress??customer.BillingAddress;ContactPerson=customer.ContactPerson;ContactPhone=customer.Phone;}
    public void Cancel(string reason,string actor,DateTimeOffset at){if(Status!=DispatchStatus.Draft)throw new InvalidOperationException("Only a Draft Dispatch can be cancelled.");if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Cancellation reason is required.");Status=DispatchStatus.Cancelled;CancellationReason=reason.Trim();CancelledBy=actor;CancelledOn=at;}
    private static string Required(string? x)=>string.IsNullOrWhiteSpace(x)?throw new ArgumentException("Required value is missing."):x.Trim();private static string? Optional(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
public sealed class DispatchPackage:BaseEntity{private DispatchPackage(){}public DispatchPackage(string number,string description,decimal? quantity,QuantityUnit? unit,decimal? net,decimal? gross,string? remarks,int sequence){PackageNumber=number.Trim();Description=description.Trim();Quantity=quantity;QuantityUnit=unit;NetWeight=net;GrossWeight=gross;Remarks=remarks;Sequence=sequence;}public Guid DispatchId{get;private set;}public string PackageNumber{get;private set;}="";public string Description{get;private set;}="";public decimal? Quantity{get;private set;}public QuantityUnit? QuantityUnit{get;private set;}public decimal? NetWeight{get;private set;}public decimal? GrossWeight{get;private set;}public decimal? Length{get;private set;}public decimal? Width{get;private set;}public decimal? Height{get;private set;}public string? Remarks{get;private set;}public int Sequence{get;private set;}}
public sealed class DispatchInventorySource:BaseEntity{private DispatchInventorySource(){}public DispatchInventorySource(Guid dispatchId,CoilType type,Guid inventoryId,string number,decimal width,decimal quantity){DispatchId=dispatchId;InventoryType=type;InventoryId=inventoryId;InventoryNumber=number;Width=width;Quantity=quantity;}public Guid DispatchId{get;private set;}public CoilType InventoryType{get;private set;}public Guid InventoryId{get;private set;}public string InventoryNumber{get;private set;}="";public decimal Width{get;private set;}public decimal Quantity{get;private set;}}
