using CoilManager.Domain.Enums;

namespace CoilManager.Application.DTOs.LaminationJobs;

public record LaminationPlateDimensionDto(Guid? Id,string DimensionCode,string? DisplayName,decimal DimensionValue,string? Unit,int Sequence,string? Remarks);
public record LaminationJobPlateDto(Guid? Id,LaminationPlateType PlateType,decimal Width,decimal? Length,int Quantity,decimal PlannedWeight,string? Remarks,IReadOnlyList<LaminationPlateDimensionDto> Dimensions);
public record LaminationJobStepDto(Guid? Id,int StepNumber,int StackQuantity,int Sequence,decimal Width,decimal PlannedWeight,string? Remarks,IReadOnlyList<LaminationJobPlateDto> Plates);
public record CreateLaminationJobRequest(string? JobOrDrawingNumber,string? Customer,string Rating,LaminationDesignType DesignType,StepLapOrientation StepLapOrientation,int NumberOfSteps,string CustomerCategory,Guid GradeId,decimal TotalWeight,decimal CustomerCoreLossPerKg,Guid? WorkOrderId,string? WorkOrderNumber,DateOnly PlannedDate,DateOnly? RequiredDate,string? Shift,string? PlannerName,string? Remarks,IReadOnlyList<LaminationJobStepDto> Steps);
public record UpdateLaminationJobRequest(string? JobOrDrawingNumber,string? Customer,string Rating,LaminationDesignType DesignType,StepLapOrientation StepLapOrientation,int NumberOfSteps,string CustomerCategory,Guid GradeId,decimal TotalWeight,decimal CustomerCoreLossPerKg,Guid? WorkOrderId,string? WorkOrderNumber,DateOnly PlannedDate,DateOnly? RequiredDate,string? Shift,string? PlannerName,string? Remarks,IReadOnlyList<LaminationJobStepDto> Steps,string RowVersion) : CreateLaminationJobRequest(JobOrDrawingNumber,Customer,Rating,DesignType,StepLapOrientation,NumberOfSteps,CustomerCategory,GradeId,TotalWeight,CustomerCoreLossPerKg,WorkOrderId,WorkOrderNumber,PlannedDate,RequiredDate,Shift,PlannerName,Remarks,Steps);
public record LaminationJobListItemDto(Guid Id,string LaminationJobNumber,string? JobOrDrawingNumber,string? Customer,string Rating,LaminationDesignType DesignType,int NumberOfSteps,string Grade,decimal TotalWeight,decimal TotalAllocatedWeight,LaminationJobStatus Status,DateOnly PlannedDate,DateTimeOffset CreatedOn);
public record LaminationJobDetailsDto(Guid Id,string LaminationJobNumber,string? JobOrDrawingNumber,string? Customer,string Rating,LaminationDesignType DesignType,StepLapOrientation StepLapOrientation,int NumberOfSteps,Guid GradeId,string Grade,decimal Thickness,string Category,decimal CoreLossPerKg,decimal TotalWeight,decimal CustomerCoreLossPerKg,decimal NoLoadLossWatts,Guid? WorkOrderId,string? WorkOrderNumber,DateOnly PlannedDate,DateOnly? RequiredDate,string Machine,string? Shift,string? PlannerName,LaminationJobStatus Status,int TotalPlannedPieces,decimal TotalPlannedWeight,decimal TotalAllocatedWeight,string? Remarks,string? DrawingAttachmentName,string? ReleasedBy,DateTimeOffset? ReleasedOn,string? AllocatedBy,DateTimeOffset? AllocatedOn,string? CancelledBy,DateTimeOffset? CancelledOn,DateTimeOffset CreatedOn,DateTimeOffset? ModifiedOn,string RowVersion,IReadOnlyList<LaminationJobStepDto> Steps);
public sealed record LaminationJobQueryRequest(int PageNumber=1,int PageSize=20,string? Search=null,LaminationJobStatus? Status=null,LaminationDesignType? DesignType=null,Guid? GradeId=null,DateOnly? PlannedFrom=null,DateOnly? PlannedTo=null,string? Customer=null,string? Rating=null);
public record LaminationMaterialRequirementDto(decimal Width,decimal RequiredWeight,decimal AllocatedWeight,decimal ShortageWeight,string Grade,decimal Thickness,IReadOnlyList<int> StepNumbers,IReadOnlyList<LaminationPlateType> PlateTypes);
public record LaminationJobMaterialAllocationDto(Guid Id,Guid SlitCoilId,string SlitCoilNumber,decimal RequiredWidth,decimal AllocatedWeight,decimal? IssuedWeight,decimal? ConsumedWeight,decimal RemainingWeightAfterAllocation,AllocationStatus Status,string ReservedBy,DateTimeOffset ReservedOn,string? ReleasedBy,DateTimeOffset? ReleasedOn,string? Remarks);
public record CreateLaminationAllocationRequest(Guid SlitCoilId,decimal RequiredWidth,decimal AllocatedWeight,bool WidthMismatchOverride=false,string? OverrideReason=null,string? Remarks=null);
public record ReleaseLaminationAllocationRequest(string? Remarks=null);
public record ConfirmLaminationAllocationRequest(bool ShortageOverride=false,string? OverrideReason=null);
public record ReleaseLaminationJobRequest(bool ShortageOverride=false,string? OverrideReason=null);
public record AvailableSlitCoilDto(Guid Id,string CoilNumber,string? MotherCoilNumber,string Grade,decimal Thickness,string Category,decimal CoreLossPerKg,decimal Width,decimal CurrentWeight,decimal ReservedWeight,decimal AvailableWeight,string Status,string? WarehouseLocation,string? SlittingJobNumber,DateTimeOffset CreatedOn);
public sealed record AvailableSlitCoilQueryRequest(string? Search=null,decimal? Width=null,string? Grade=null,decimal? Thickness=null,decimal? AvailableWeight=null,string? Warehouse=null,string? Status=null);
public record LaminationMetricsDto(int Draft,int ReleasedAwaitingAllocation,int AllocatedReadyForCompletion,int CompletedToday,int MaterialShortage,int Cancelled,IReadOnlyList<LaminationQueueItemDto> Queue);
public record LaminationQueueItemDto(Guid Id,string JobNumber,string? DrawingNumber,string Rating,LaminationJobStatus Status,decimal AllocationPercentage,DateOnly PlannedDate,string? Machine,string? Shift);

public record LaminationAllocationConsumptionRequest(Guid AllocationId,decimal ActualConsumedWeight,string? Remarks=null);
public record LaminationPlateResultRequest(Guid StepId,LaminationPlateType PlateType,int PlannedQuantity,int GoodQuantity,int RejectedQuantity,decimal? ActualWeight=null,string? Remarks=null);
public record CompleteLaminationJobRequest(string RowVersion,IReadOnlyList<LaminationAllocationConsumptionRequest> Allocations,IReadOnlyList<LaminationPlateResultRequest> PlateResults,int TotalGoodPieces,int TotalRejectedPieces,decimal TotalConsumedWeight,decimal TotalScrapWeight,string? CompletionRemarks=null);
public record LaminationCompletionDto(Guid JobId,string JobNumber,int TotalGoodPieces,int TotalRejectedPieces,decimal TotalConsumedWeight,decimal TotalScrapWeight,string? CompletedBy,DateTimeOffset? CompletedOn,string? CompletionRemarks,IReadOnlyList<LaminationJobMaterialAllocationDto> Allocations);