<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoilManager.Domain\CoilManager.Domain.csproj" />
    <ProjectReference Include="..\CoilManager.Shared\CoilManager.Shared.csproj" />
  </ItemGroup>

</Project>
