export enum SalesOrderStatus { Draft, Confirmed, InPlanning, InProduction, PartiallyReady, ReadyForDispatch, PartiallyDispatched, Completed, OnHold, Cancelled }
export enum SalesOrderPriority { Low, Normal, High, Urgent }
export enum SalesOrderProductType { MotherCoil, SlitCoil, Lamination, CoreFrameAssembly }
export enum QuantityUnit { Kg, Pieces, Sets }
export const statusLabels=['Draft','Confirmed','In Planning','In Production','Partially Ready','Ready for Dispatch','Partially Dispatched','Completed','On Hold','Cancelled'];
export const priorityLabels=['Low','Normal','High','Urgent'];
export const productLabels=['Mother Coil','Slit Coil','Lamination','Core Frame Assembly'];
export const unitLabels=['Kg','Pieces','Sets'];
export interface ApiResponse<T>{success:boolean;message:string;data:T|null;errors:readonly string[]}
export interface ApiPagedResponse<T>{success:boolean;message:string;data:readonly T[];pagination:{pageNumber:number;pageSize:number;totalCount:number;totalPages:number};errors:readonly string[]}
export interface Customer{id:string;customerCode:string;customerName:string;shortName?:string;billingAddress:string;shippingAddress?:string;city:string;state:string;country:string;postalCode:string;contactPerson:string;phone:string;email:string;gstNumber?:string;pan?:string;paymentTerms?:string;creditDays?:number;isActive:boolean;remarks?:string;createdBy?:string;createdOn:string;modifiedBy?:string;modifiedOn?:string;rowVersion:string}
export type CustomerRequest=Omit<Customer,'id'|'customerCode'|'createdBy'|'createdOn'|'modifiedBy'|'modifiedOn'>;
export interface SalesOrderLine{id?:string;lineNumber:number;productType:SalesOrderProductType;description:string;gradeId?:string;gradeCode?:string;thickness?:number;category?:string;coreLossPerKg?:number;width?:number;length?:number;drawingNumber?:string;drawingRevision?:string;oemJobNumber?:string;transformerRating?:string;orderedQuantity:number;quantityUnit:QuantityUnit;unitPrice?:number;lineAmount?:number;requiredDeliveryDate?:string;customerItemReference?:string;remarks?:string;drawingAttachmentName?:string;fulfilledQuantity?:number;readyQuantity?:number;dispatchedQuantity?:number;workOrderStatus?:string}
export interface SalesOrder{id:string;salesOrderNumber:string;customerId:string;customerCode:string;customerName:string;customerPONumber:string;customerPODate?:string;orderDate:string;requiredDeliveryDate:string;currency:string;paymentTerms?:string;billingAddress:string;shippingAddress:string;contactPerson?:string;contactPhone?:string;contactEmail?:string;status:SalesOrderStatus;priority:SalesOrderPriority;totalLines:number;totalWeightKg:number;totalPieces:number;totalSets:number;subtotal?:number;taxAmount?:number;totalAmount?:number;customerRemarks?:string;internalRemarks?:string;confirmedBy?:string;confirmedOn?:string;cancelledBy?:string;cancelledOn?:string;cancellationReason?:string;createdBy?:string;createdOn:string;modifiedBy?:string;modifiedOn?:string;rowVersion:string;lines:readonly SalesOrderLine[]}
export interface SalesOrderRequest{customerId:string;customerPONumber:string;customerPODate?:string|null;orderDate:string;requiredDeliveryDate:string;currency:string;paymentTerms?:string|null;billingAddress:string;shippingAddress:string;contactPerson?:string|null;contactPhone?:string|null;contactEmail?:string|null;priority:SalesOrderPriority;taxAmount?:number|null;customerRemarks?:string|null;internalRemarks?:string|null;lines:readonly SalesOrderLine[];rowVersion?:string|null}
