using CoilManager.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace CoilManager.Persistence.Configurations;
public sealed class LaminationJobConfiguration : IEntityTypeConfiguration<LaminationJob>
{
 public void Configure(EntityTypeBuilder<LaminationJob> b) { b.ToTable("LaminationJobs","app"); b.HasKey(x=>x.Id); b.HasIndex(x=>x.LaminationJobNumber).IsUnique(); b.HasIndex(x=>x.JobOrDrawingNumber); b.HasIndex(x=>x.Status); b.HasIndex(x=>x.PlannedDate); b.HasIndex(x=>x.GradeId); b.Ignore(x=>x.Machine); b.Property(x=>x.LaminationJobNumber).HasMaxLength(30).IsRequired(); b.Property(x=>x.JobOrDrawingNumber).HasMaxLength(100); b.Property(x=>x.Customer).HasMaxLength(200); b.Property(x=>x.Rating).HasMaxLength(100).IsRequired(); b.Property(x=>x.Category).HasMaxLength(20); b.Property(x=>x.Thickness).HasPrecision(18,3); b.Property(x=>x.CoreLossPerKg).HasPrecision(18,4); b.Property(x=>x.TotalWeight).HasPrecision(18,3); b.Property(x=>x.CustomerCoreLossPerKg).HasPrecision(18,4); b.Property(x=>x.NoLoadLossWatts).HasPrecision(18,2); b.Property(x=>x.TotalPlannedWeight).HasPrecision(18,3); b.Property(x=>x.TotalAllocatedWeight).HasPrecision(18,3); b.Property(x=>x.TotalConsumedWeight).HasPrecision(18,3); b.Property(x=>x.TotalScrapWeight).HasPrecision(18,3); b.Property(x=>x.CompletionRemarks).HasMaxLength(2000); b.Property(x=>x.Status).HasConversion<string>(); b.Property(x=>x.DesignType).HasConversion<string>(); b.Property(x=>x.StepLapOrientation).HasConversion<string>(); b.Property(x=>x.RowVersion).IsRowVersion(); b.HasOne(x=>x.Grade).WithMany().HasForeignKey(x=>x.GradeId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x=>x.Steps).WithOne().HasForeignKey(x=>x.LaminationJobId).OnDelete(DeleteBehavior.Cascade); b.HasMany(x=>x.Allocations).WithOne().HasForeignKey(x=>x.LaminationJobId).OnDelete(DeleteBehavior.Cascade); }
}
public sealed class LaminationJobStepConfiguration : IEntityTypeConfiguration<LaminationJobStep> { public void Configure(EntityTypeBuilder<LaminationJobStep>b) { b.ToTable("LaminationJobSteps","app"); b.HasKey(x=>x.Id); b.HasIndex(x=>x.LaminationJobId); b.HasIndex(x=>new{x.LaminationJobId,x.StepNumber}).IsUnique(); b.Property(x=>x.Width).HasPrecision(18,3); b.Property(x=>x.PlannedWeight).HasPrecision(18,3); b.HasMany(x=>x.Plates).WithOne().HasForeignKey(x=>x.LaminationJobStepId).OnDelete(DeleteBehavior.Cascade); } }
public sealed class LaminationJobPlateConfiguration : IEntityTypeConfiguration<LaminationJobPlate> { public void Configure(EntityTypeBuilder<LaminationJobPlate>b) { b.ToTable("LaminationJobPlates","app"); b.HasKey(x=>x.Id); b.HasIndex(x=>x.LaminationJobStepId); b.HasIndex(x=>new{x.LaminationJobStepId,x.PlateType}).IsUnique(); b.Property(x=>x.PlateType).HasConversion<string>(); b.Property(x=>x.Width).HasPrecision(18,3); b.Property(x=>x.Length).HasPrecision(18,3); b.Property(x=>x.PlannedWeight).HasPrecision(18,3); b.HasMany(x=>x.Dimensions).WithOne().HasForeignKey(x=>x.LaminationJobPlateId).OnDelete(DeleteBehavior.Cascade); } }
public sealed class LaminationPlateDimensionConfiguration : IEntityTypeConfiguration<LaminationPlateDimension> { public void Configure(EntityTypeBuilder<LaminationPlateDimension>b) { b.ToTable("LaminationPlateDimensions","app"); b.HasKey(x=>x.Id); b.HasIndex(x=>new{x.LaminationJobPlateId,x.DimensionCode}).IsUnique(); b.Property(x=>x.DimensionCode).HasMaxLength(50).IsRequired(); b.Property(x=>x.DimensionValue).HasPrecision(18,3); b.Property(x=>x.Unit).HasMaxLength(20).HasDefaultValue("mm"); } }
public sealed class LaminationJobMaterialAllocationConfiguration : IEntityTypeConfiguration<LaminationJobMaterialAllocation> { public void Configure(EntityTypeBuilder<LaminationJobMaterialAllocation>b) { b.ToTable("LaminationJobMaterialAllocations","app"); b.HasKey(x=>x.Id); b.HasIndex(x=>x.LaminationJobId); b.HasIndex(x=>x.SlitCoilId); b.Property(x=>x.Status).HasConversion<string>(); b.Property(x=>x.RequiredWidth).HasPrecision(18,3); b.Property(x=>x.AllocatedWeight).HasPrecision(18,3); b.Property(x=>x.IssuedWeight).HasPrecision(18,3); b.Property(x=>x.ConsumedWeight).HasPrecision(18,3); b.Property(x=>x.RemainingWeightAfterAllocation).HasPrecision(18,3); b.Property(x=>x.SlitCoilNumber).HasMaxLength(60); } }
