using CoilManager.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CoilManager.Persistence.Configurations;

public sealed class CustomerConfiguration:IEntityTypeConfiguration<Customer>
{
 public void Configure(EntityTypeBuilder<Customer> b){b.ToTable("Customers","sales");b.HasKey(x=>x.Id);b.Property(x=>x.CustomerCode).HasMaxLength(20).IsRequired();b.HasIndex(x=>x.CustomerCode).IsUnique();b.HasIndex(x=>x.CustomerName);b.HasIndex(x=>x.IsActive);b.Property(x=>x.CustomerName).HasMaxLength(200).IsRequired();b.Property(x=>x.ShortName).HasMaxLength(80);b.Property(x=>x.BillingAddress).HasMaxLength(1000).IsRequired();b.Property(x=>x.ShippingAddress).HasMaxLength(1000);b.Property(x=>x.City).HasMaxLength(100);b.Property(x=>x.State).HasMaxLength(100);b.Property(x=>x.Country).HasMaxLength(100);b.Property(x=>x.PostalCode).HasMaxLength(20);b.Property(x=>x.ContactPerson).HasMaxLength(160);b.Property(x=>x.Phone).HasMaxLength(40);b.Property(x=>x.Email).HasMaxLength(254);b.Property(x=>x.GSTNumber).HasMaxLength(30);b.Property(x=>x.PAN).HasMaxLength(20);b.Property(x=>x.PaymentTerms).HasMaxLength(250);b.Property(x=>x.Remarks).HasMaxLength(2000);b.Property(x=>x.RowVersion).IsRowVersion();}
}
public sealed class SalesOrderConfiguration:IEntityTypeConfiguration<SalesOrder>
{
 public void Configure(EntityTypeBuilder<SalesOrder> b){b.ToTable("SalesOrders","sales");b.HasKey(x=>x.Id);b.Property(x=>x.SalesOrderNumber).HasMaxLength(30).IsRequired();b.HasIndex(x=>x.SalesOrderNumber).IsUnique();b.HasIndex(x=>x.CustomerId);b.HasIndex(x=>x.Status);b.HasIndex(x=>x.OrderDate);b.HasIndex(x=>x.RequiredDeliveryDate);b.HasIndex(x=>x.CustomerPONumber);b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Priority).HasConversion<string>().HasMaxLength(20);b.Property(x=>x.CustomerCode).HasMaxLength(20);b.Property(x=>x.CustomerName).HasMaxLength(200);b.Property(x=>x.CustomerPONumber).HasMaxLength(100);b.Property(x=>x.Currency).HasMaxLength(3);b.Property(x=>x.BillingAddress).HasMaxLength(1000);b.Property(x=>x.ShippingAddress).HasMaxLength(1000);b.Property(x=>x.PaymentTerms).HasMaxLength(250);b.Property(x=>x.TaxAmount).HasPrecision(18,2);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Customer).WithMany().HasForeignKey(x=>x.CustomerId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.Lines).WithOne(x=>x.SalesOrder).HasForeignKey(x=>x.SalesOrderId).OnDelete(DeleteBehavior.Cascade);b.Navigation(x=>x.Lines).UsePropertyAccessMode(PropertyAccessMode.Field);b.Ignore(x=>x.TotalLines);b.Ignore(x=>x.TotalOrderWeight);b.Ignore(x=>x.TotalOrderPieces);b.Ignore(x=>x.Subtotal);b.Ignore(x=>x.TotalAmount);}
}
public sealed class SalesOrderLineConfiguration:IEntityTypeConfiguration<SalesOrderLine>
{
 public void Configure(EntityTypeBuilder<SalesOrderLine> b){b.ToTable("SalesOrderLines","sales");b.HasKey(x=>x.Id);b.HasIndex(x=>x.SalesOrderId);b.HasIndex(x=>new{x.SalesOrderId,x.LineNumber}).IsUnique();b.Property(x=>x.ProductType).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.QuantityUnit).HasConversion<string>().HasMaxLength(20);foreach(var p in new[]{nameof(SalesOrderLine.Thickness),nameof(SalesOrderLine.Width),nameof(SalesOrderLine.Length),nameof(SalesOrderLine.OrderedQuantity),nameof(SalesOrderLine.FulfilledQuantity),nameof(SalesOrderLine.ReadyQuantity),nameof(SalesOrderLine.DispatchedQuantity)})b.Property(p).HasPrecision(18,3);b.Property(x=>x.CoreLossPerKg).HasPrecision(18,4);b.Property(x=>x.UnitPrice).HasPrecision(18,2);b.Property(x=>x.LineAmount).HasPrecision(18,2);b.Property(x=>x.Description).HasMaxLength(500);b.Property(x=>x.DrawingAttachmentName).HasMaxLength(260);b.Property(x=>x.DrawingAttachmentPath).HasMaxLength(260);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Grade).WithMany().HasForeignKey(x=>x.GradeId).OnDelete(DeleteBehavior.Restrict);}
}
