import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button'; import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input'; import { MatSelectModule } from '@angular/material/select';
import { Role } from '../../../core/auth/auth.models'; import { SecurityAdminService } from './security-admin.service';
@Component({selector:'app-create-user-dialog',imports:[ReactiveFormsModule,MatDialogModule,MatButtonModule,MatCheckboxModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSelectModule],template:`<h2 mat-dialog-title><mat-icon>person_add</mat-icon>Create user</h2><mat-dialog-content><p class="intro">Create an ERP account and assign access through roles.</p><form [formGroup]="form" id="create-user-form" (ngSubmit)="save()"><div class="grid"><mat-form-field appearance="outline"><mat-label>Full name</mat-label><input matInput formControlName="displayName"><mat-error>Full name is required</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"><mat-error>Enter a valid email</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>Phone number</mat-label><input matInput formControlName="phoneNumber"></mat-form-field><mat-form-field appearance="outline"><mat-label>Job title</mat-label><input matInput formControlName="jobTitle"></mat-form-field><mat-form-field appearance="outline" class="full"><mat-label>Roles</mat-label><mat-select formControlName="roles" multiple>@for(role of data.roles;track role.id){<mat-option [value]="role.name">{{role.name}}</mat-option>}</mat-select><mat-hint>Permissions are inherited from roles.</mat-hint><mat-error>Select at least one role</mat-error></mat-form-field><mat-form-field appearance="outline" class="full"><mat-label>Temporary password</mat-label><input matInput [type]="showPassword()?'text':'password'" formControlName="temporaryPassword"><button mat-icon-button matSuffix type="button" (click)="showPassword.set(!showPassword())"><mat-icon>{{showPassword()?'visibility_off':'visibility'}}</mat-icon></button><mat-hint>12+ characters with upper/lower case, number and symbol.</mat-hint></mat-form-field></div><mat-checkbox formControlName="mustChangePassword">Require password change at next login</mat-checkbox>@if(error()){<div class="error" role="alert"><mat-icon>error</mat-icon><span>{{error()}}</span></div>}</form></mat-dialog-content><mat-dialog-actions align="end"><button mat-stroked-button type="button" mat-dialog-close>Cancel</button><button mat-flat-button type="submit" form="create-user-form" [disabled]="form.invalid||saving()">{{saving()?'Creating…':'Create user'}}</button></mat-dialog-actions>`,styles:[`h2{display:flex!important;align-items:center;gap:10px}mat-dialog-content{width:min(680px,80vw)}.intro{margin-top:0;color:#667085}.grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 16px;padding-top:8px}.full{grid-column:1/-1}.error{display:flex;gap:8px;align-items:center;margin-top:14px;padding:10px 12px;border:1px solid #f2b8b5;border-radius:6px;background:#fff7f6;color:#ba1a1a}mat-dialog-actions{padding:16px 24px 22px}button{border-radius:6px}@media(max-width:650px){mat-dialog-content{width:auto}.grid{grid-template-columns:1fr}.full{grid-column:auto}}`]})
export class CreateUserDialogComponent{private api=inject(SecurityAdminService);private ref=inject(MatDialogRef<CreateUserDialogComponent>);readonly data=inject<{roles:Role[]}>(MAT_DIALOG_DATA);saving=signal(false);error=signal('');showPassword=signal(false);form=new FormGroup({displayName:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(160)]}),email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),phoneNumber:new FormControl<string|null>(null),jobTitle:new FormControl<string|null>(null),roles:new FormControl<string[]>([],{nonNullable:true,validators:Validators.required}),temporaryPassword:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(12)]}),mustChangePassword:new FormControl(true,{nonNullable:true})});save(){if(this.form.invalid)return;this.saving.set(true);this.error.set('');this.api.createUser(this.form.getRawValue()).subscribe({next:()=>this.ref.close(true),error:e=>{this.error.set(e.error?.errors?.join(' ')||e.error?.message||'Unable to create user.');this.saving.set(false);}});}}
