import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input'; import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSelectModule } from '@angular/material/select';
import { Role } from '../../../core/auth/auth.models'; import { SecurityAdminService } from './security-admin.service';

@Component({selector:'app-user-edit-page',imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatCardModule,MatFormFieldModule,MatIconModule,MatInputModule,MatProgressBarModule,MatSelectModule],template:`
<section class="page-title-bar"><div><h1>Edit User</h1><nav><a routerLink="/dashboard">Home</a><mat-icon>chevron_right</mat-icon><a routerLink="/admin/users">Security & Access</a><mat-icon>chevron_right</mat-icon><strong>Edit User</strong></nav></div></section>
<section class="form-page"><mat-card appearance="outlined">@if(loading()){<mat-progress-bar mode="indeterminate"/>}<form [formGroup]="form" (ngSubmit)="save()"><div class="section-heading"><mat-icon>person</mat-icon><div><h2>User details</h2><p>Update the employee profile and role-based ERP access.</p></div></div><div class="form-grid">
<mat-form-field appearance="outline"><mat-label>Full name</mat-label><input matInput formControlName="displayName" autocomplete="name"><mat-error>Full name is required</mat-error></mat-form-field>
<mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput formControlName="email" readonly><mat-hint>Email is the login identifier and cannot be changed.</mat-hint></mat-form-field>
<mat-form-field appearance="outline"><mat-label>Phone number</mat-label><input matInput formControlName="phoneNumber" autocomplete="tel"></mat-form-field>
<mat-form-field appearance="outline"><mat-label>Job title</mat-label><input matInput formControlName="jobTitle"></mat-form-field>
<mat-form-field appearance="outline" class="full-width"><mat-label>Roles</mat-label><mat-select formControlName="roles" multiple>@for(role of roles();track role.id){<mat-option [value]="role.name">{{role.name}}</mat-option>}</mat-select><mat-hint>Permissions are inherited through the selected roles.</mat-hint><mat-error>Select at least one role</mat-error></mat-form-field>
</div>@if(error()){<div class="error-box" role="alert"><mat-icon>error</mat-icon><span>{{error()}}</span></div>}<div class="form-actions"><a mat-stroked-button [routerLink]="['/admin/users',userId]">Cancel</a><button mat-flat-button type="submit" [disabled]="form.invalid||saving()"><mat-icon>save</mat-icon>{{saving()?'Saving…':'Save Changes'}}</button></div></form></mat-card></section>`,styleUrl:'./user-edit-page.component.scss'})
export class UserEditPageComponent{private api=inject(SecurityAdminService);private route=inject(ActivatedRoute);private router=inject(Router);readonly userId=this.route.snapshot.paramMap.get('id')!;loading=signal(true);saving=signal(false);error=signal('');roles=signal<Role[]>([]);form=new FormGroup({displayName:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(160)]}),email:new FormControl({value:'',disabled:true},{nonNullable:true}),phoneNumber:new FormControl<string|null>(null),jobTitle:new FormControl<string|null>(null),roles:new FormControl<string[]>([],{nonNullable:true,validators:Validators.required})});constructor(){this.api.roles().subscribe(x=>this.roles.set(x.data));this.api.user(this.userId).subscribe({next:x=>{this.form.patchValue({displayName:x.data.displayName,email:x.data.email,phoneNumber:x.data.phoneNumber??null,jobTitle:x.data.jobTitle??null,roles:x.data.roles});this.loading.set(false);},error:e=>{this.error.set(e.error?.message??'Unable to load user.');this.loading.set(false);}});}save(){if(this.form.invalid)return;this.saving.set(true);this.error.set('');const value=this.form.getRawValue();this.api.updateUser(this.userId,{displayName:value.displayName,phoneNumber:value.phoneNumber,jobTitle:value.jobTitle,roles:value.roles}).subscribe({next:()=>void this.router.navigate(['/admin/users',this.userId]),error:e=>{this.error.set(e.error?.errors?.join(' ')||e.error?.message||'Unable to update user.');this.saving.set(false);}});}}
