using System.Security.Claims;
using CoilManager.Application.DTOs.Sales;
using CoilManager.Domain.Entities;
using CoilManager.Domain.Enums;
using CoilManager.Persistence;
using CoilManager.Shared.Pagination;
using CoilManager.Shared.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoilManager.API.Controllers;

[Route("api/sales-orders"),Authorize]
public sealed class SalesOrdersController(ApplicationDbContext db,IWebHostEnvironment environment):BaseApiController
{
 [HttpGet] public async Task<ActionResult<ApiPagedResponse<SalesOrderDto>>> List(string? search,Guid? customerId,SalesOrderStatus? status,SalesOrderPriority? priority,DateOnly? orderDateFrom,DateOnly? orderDateTo,DateOnly? deliveryDateFrom,DateOnly? deliveryDateTo,SalesOrderProductType? productType,int page=1,int pageSize=25,CancellationToken ct=default)
 {var q=db.SalesOrders.AsNoTracking().Include(x=>x.Lines).AsQueryable();if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.SalesOrderNumber.Contains(search)||x.CustomerName.Contains(search)||x.CustomerPONumber.Contains(search));if(customerId.HasValue)q=q.Where(x=>x.CustomerId==customerId);if(status.HasValue)q=q.Where(x=>x.Status==status);if(priority.HasValue)q=q.Where(x=>x.Priority==priority);if(orderDateFrom.HasValue)q=q.Where(x=>x.OrderDate>=orderDateFrom);if(orderDateTo.HasValue)q=q.Where(x=>x.OrderDate<=orderDateTo);if(deliveryDateFrom.HasValue)q=q.Where(x=>x.RequiredDeliveryDate>=deliveryDateFrom);if(deliveryDateTo.HasValue)q=q.Where(x=>x.RequiredDeliveryDate<=deliveryDateTo);if(productType.HasValue)q=q.Where(x=>x.Lines.Any(l=>l.ProductType==productType));int total=await q.CountAsync(ct);page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var rows=await q.OrderByDescending(x=>x.OrderDate).ThenByDescending(x=>x.SalesOrderNumber).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(ct);return Paged(rows.Select(Map).ToList(),new(page,pageSize,total));}
 [HttpGet("{id:guid}")] public async Task<ActionResult<ApiResponse<SalesOrderDto>>> Get(Guid id,CancellationToken ct){var x=await Query().FirstOrDefaultAsync(x=>x.Id==id,ct);return x is null?Failure<SalesOrderDto>(404,"Sales Order was not found."):Success(Map(x));}
 [HttpGet("by-number/{*number}")] public async Task<ActionResult<ApiResponse<SalesOrderDto>>> ByNumber(string number,CancellationToken ct){var x=await Query().FirstOrDefaultAsync(x=>x.SalesOrderNumber==number,ct);return x is null?Failure<SalesOrderDto>(404,"Sales Order was not found."):Success(Map(x));}
 [HttpGet("next-number")] public async Task<ActionResult<ApiResponse<string>>> Next(CancellationToken ct)=>Success(await NextNumber(DateTime.UtcNow.Year,ct));
 [HttpPost,Authorize(Policy="Permission:SalesOrders.Create")] public async Task<ActionResult<ApiResponse<SalesOrderDto>>> Create(SaveSalesOrderRequest r,CancellationToken ct){var built=await Build(null,r,ct);if(built.Error!=null)return Failure<SalesOrderDto>(400,built.Error,[built.Error]);db.SalesOrders.Add(built.Order!);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(Get),new{id=built.Order!.Id},ApiResponse<SalesOrderDto>.Ok(Map(built.Order),"Sales Order draft created."));}
 [HttpPut("{id:guid}"),Authorize(Policy="Permission:SalesOrders.Edit")] public async Task<ActionResult<ApiResponse<SalesOrderDto>>> Update(Guid id,SaveSalesOrderRequest r,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);var x=await Query(true).FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return Failure<SalesOrderDto>(404,"Sales Order was not found.");if(!VersionMatches(x.RowVersion,r.RowVersion))return Failure<SalesOrderDto>(409,"Sales Order was changed by another user. Reload the order and try again.");var attachments=x.Lines.Where(l=>!string.IsNullOrWhiteSpace(l.DrawingAttachmentPath)).ToDictionary(l=>l.LineNumber,l=>(l.DrawingAttachmentName!,l.DrawingAttachmentPath!));db.SalesOrderLines.RemoveRange(x.Lines);await db.SaveChangesAsync(ct);var built=await Build(x,r,ct);if(built.Error!=null)return Failure<SalesOrderDto>(400,built.Error,[built.Error]);foreach(var line in x.Lines){if(attachments.TryGetValue(line.LineNumber,out var attachment))line.SetDrawingAttachment(attachment.Item1,attachment.Item2);db.Entry(line).State=EntityState.Added;}await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Success(Map(x),"Sales Order updated.");}
 [HttpPost("{id:guid}/lines/{lineId:guid}/drawing"),Authorize(Policy="Permission:SalesOrders.Edit"),RequestSizeLimit(15*1024*1024)] public async Task<ActionResult<ApiResponse<object>>> UploadDrawing(Guid id,Guid lineId,IFormFile file,CancellationToken ct){var line=await db.SalesOrderLines.FirstOrDefaultAsync(x=>x.Id==lineId&&x.SalesOrderId==id,ct);if(line is null)return Failure<object>(404,"Sales Order line was not found.");if(line.ProductType!=SalesOrderProductType.Lamination)return Failure<object>(400,"Drawing attachments are available only for Lamination items.");string ext=Path.GetExtension(file.FileName).ToLowerInvariant();if(file.Length<=0||file.Length>15*1024*1024||ext is not (".pdf" or ".png" or ".jpg" or ".jpeg"))return Failure<object>(400,"Drawing must be a PDF, PNG, JPG or JPEG up to 15 MB.");string dir=Path.Combine(environment.ContentRootPath,"App_Data","sales-order-drawings");Directory.CreateDirectory(dir);string stored=$"{lineId:N}-{Guid.NewGuid():N}{ext}";await using(var stream=System.IO.File.Create(Path.Combine(dir,stored)))await file.CopyToAsync(stream,ct);line.SetDrawingAttachment(Path.GetFileName(file.FileName),stored);await db.SaveChangesAsync(ct);return Success<object>(null,"Drawing attached.");}
 [HttpGet("{id:guid}/lines/{lineId:guid}/drawing")] public async Task<IActionResult> DownloadDrawing(Guid id,Guid lineId,CancellationToken ct){var line=await db.SalesOrderLines.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==lineId&&x.SalesOrderId==id,ct);if(line is null||string.IsNullOrWhiteSpace(line.DrawingAttachmentPath))return NotFound();string path=Path.Combine(environment.ContentRootPath,"App_Data","sales-order-drawings",Path.GetFileName(line.DrawingAttachmentPath));if(!System.IO.File.Exists(path))return NotFound();string contentType=Path.GetExtension(path).ToLowerInvariant() switch{".pdf"=>"application/pdf",".png"=>"image/png",".jpg" or ".jpeg"=>"image/jpeg",_=>"application/octet-stream"};return PhysicalFile(path,contentType,line.DrawingAttachmentName??"drawing");} [HttpDelete("{id:guid}"),Authorize(Policy="Permission:SalesOrders.Edit")] public async Task<ActionResult> Delete(Guid id,CancellationToken ct){var x=await db.SalesOrders.FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(x.Status!=SalesOrderStatus.Draft)return Conflict(ApiResponse<object>.Fail("Confirmed or non-draft Sales Orders cannot be deleted."));db.Remove(x);await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPost("{id:guid}/confirm"),Authorize(Policy="Permission:SalesOrders.Confirm")] public Task<ActionResult<ApiResponse<SalesOrderDto>>> Confirm(Guid id,CancellationToken ct)=>Transition(id,x=>x.Confirm(Actor,DateTimeOffset.UtcNow),ct);
 [HttpPost("{id:guid}/hold"),Authorize(Policy="Permission:SalesOrders.Hold")] public Task<ActionResult<ApiResponse<SalesOrderDto>>> Hold(Guid id,CancellationToken ct)=>Transition(id,x=>x.Hold(),ct);
 [HttpPost("{id:guid}/release-hold"),Authorize(Policy="Permission:SalesOrders.Hold")] public Task<ActionResult<ApiResponse<SalesOrderDto>>> Release(Guid id,CancellationToken ct)=>Transition(id,x=>x.ReleaseHold(),ct);
 [HttpPost("{id:guid}/cancel"),Authorize(Policy="Permission:SalesOrders.Cancel")] public Task<ActionResult<ApiResponse<SalesOrderDto>>> Cancel(Guid id,CancelSalesOrderRequest r,CancellationToken ct)=>Transition(id,x=>x.Cancel(r.Reason,Actor,DateTimeOffset.UtcNow),ct,r.RowVersion);
 private string Actor=>User.FindFirstValue(ClaimTypes.Email)??User.Identity?.Name??"System";
 private IQueryable<SalesOrder> Query(bool tracking=false){var q=tracking?db.SalesOrders.AsQueryable():db.SalesOrders.AsNoTracking();return q.Include(x=>x.Customer).Include(x=>x.Lines);}
 private async Task<ActionResult<ApiResponse<SalesOrderDto>>> Transition(Guid id,Action<SalesOrder> action,CancellationToken ct,string? version=null){var x=await Query(true).FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return Failure<SalesOrderDto>(404,"Sales Order was not found.");SetVersion(x,version);try{action(x);await db.SaveChangesAsync(ct);return Success(Map(x),"Sales Order status updated.");}catch(Exception ex)when(ex is InvalidOperationException or ArgumentException){return Failure<SalesOrderDto>(400,ex.Message,[ex.Message]);}}
 private async Task<(SalesOrder? Order,string? Error)> Build(SalesOrder? existing,SaveSalesOrderRequest r,CancellationToken ct){var customer=await db.Customers.FirstOrDefaultAsync(x=>x.Id==r.CustomerId,ct);if(customer is null)return(null,"Customer was not found.");if(existing is null&&!customer.IsActive)return(null,"Inactive customers cannot be selected on new Sales Orders.");if(string.IsNullOrWhiteSpace(r.CustomerPONumber)||string.IsNullOrWhiteSpace(r.BillingAddress)||string.IsNullOrWhiteSpace(r.ShippingAddress))return(null,"Customer PO number and addresses are required.");if(r.Lines.Count==0)return(null,"At least one Sales Order line is required.");if(r.Lines.Select(x=>x.LineNumber).Distinct().Count()!=r.Lines.Count)return(null,"Duplicate line numbers are not allowed.");var lines=new List<SalesOrderLine>();foreach(var input in r.Lines){var result=await BuildLine(input,ct);if(result.Error!=null)return(null,$"Line {input.LineNumber}: {result.Error}");lines.Add(result.Line!);}var order=existing??new SalesOrder(await NextNumber(r.OrderDate.Year,ct),customer,r.CustomerPONumber,r.CustomerPODate,r.OrderDate,r.RequiredDeliveryDate,r.Currency,r.Priority);order.Update(customer,r.CustomerPONumber,r.CustomerPODate,r.OrderDate,r.RequiredDeliveryDate,r.Currency,r.Priority,r.PaymentTerms,r.BillingAddress,r.ShippingAddress,r.ContactPerson,r.ContactPhone,r.ContactEmail,r.TaxAmount,r.CustomerRemarks,r.InternalRemarks,lines);return(order,null);}
 private async Task<(SalesOrderLine? Line,string? Error)> BuildLine(SalesOrderLineRequest r,CancellationToken ct){if(r.OrderedQuantity<=0)return(null,"Quantity must be greater than zero.");if(!r.UnitPrice.HasValue||r.UnitPrice<0)return(null,"Unit Price is required and cannot be negative.");if(r.ProductType==SalesOrderProductType.CoreFrameAssembly)return(null,"Core Frame Assembly is future-ready and cannot be ordered in this sprint.");if(r.ProductType is SalesOrderProductType.MotherCoil or SalesOrderProductType.SlitCoil or SalesOrderProductType.Lamination && r.QuantityUnit!=QuantityUnit.Kg)return(null,"Mother Coil, Slit Coil and Lamination lines must use Kg.");if(r.ProductType==SalesOrderProductType.Lamination&&string.IsNullOrWhiteSpace(r.DrawingNumber)&&string.IsNullOrWhiteSpace(r.OEMJobNumber))return(null,"Drawing Number or OEM Job Number is required.");if(r.ProductType==SalesOrderProductType.Lamination&&string.IsNullOrWhiteSpace(r.TransformerRating))return(null,"Transformer Rating is required.");if(!r.GradeId.HasValue)return(null,"Grade is required.");var grade=await db.Grades.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==r.GradeId&&x.IsActive,ct);if(grade is null)return(null,"An active Grade is required.");if(r.ProductType is SalesOrderProductType.MotherCoil or SalesOrderProductType.SlitCoil && (!r.Width.HasValue||r.Width<=0))return(null,"Width is required and must be positive.");return(new(r.LineNumber,r.ProductType,r.Description,r.GradeId,grade.Code,grade.ThicknessMm,grade.Category,grade.CoreLossPerKg,r.Width,r.Length,r.DrawingNumber,null,r.OEMJobNumber,r.TransformerRating,r.OrderedQuantity,r.QuantityUnit,r.UnitPrice,r.RequiredDeliveryDate,null,r.Remarks),null);}
 private async Task<string> NextNumber(int year,CancellationToken ct){string prefix=$"SO/{year}/";string? last=await db.SalesOrders.Where(x=>x.SalesOrderNumber.StartsWith(prefix)).OrderByDescending(x=>x.SalesOrderNumber).Select(x=>x.SalesOrderNumber).FirstOrDefaultAsync(ct);int n=int.TryParse(last?.Split('/').Last(),out var value)?value+1:1;return $"{prefix}{n:00000}";}
 private static bool VersionMatches(byte[] current,string? submitted){if(string.IsNullOrWhiteSpace(submitted))return false;try{return current.AsSpan().SequenceEqual(Convert.FromBase64String(submitted));}catch(FormatException){return false;}}
 private void SetVersion(SalesOrder x,string? v){if(!string.IsNullOrWhiteSpace(v))db.Entry(x).Property(y=>y.RowVersion).OriginalValue=Convert.FromBase64String(v);}
 private static SalesOrderDto Map(SalesOrder x){var lines=x.Lines.OrderBy(l=>l.LineNumber).Select(l=>new SalesOrderLineDto(l.Id,l.LineNumber,l.ProductType,l.Description,l.GradeId,l.GradeCode,l.Thickness,l.Category,l.CoreLossPerKg,l.Width,l.Length,l.DrawingNumber,l.DrawingRevision,l.OEMJobNumber,l.TransformerRating,l.OrderedQuantity,l.QuantityUnit,l.UnitPrice,l.LineAmount,l.RequiredDeliveryDate,l.CustomerItemReference,l.Remarks,l.DrawingAttachmentName,l.FulfilledQuantity,l.ReadyQuantity,l.DispatchedQuantity,l.WorkOrderStatus)).ToList();decimal kg=lines.Where(l=>l.QuantityUnit==QuantityUnit.Kg).Sum(l=>l.OrderedQuantity),pieces=lines.Where(l=>l.QuantityUnit==QuantityUnit.Pieces).Sum(l=>l.OrderedQuantity),sets=lines.Where(l=>l.QuantityUnit==QuantityUnit.Sets).Sum(l=>l.OrderedQuantity);decimal? subtotal=lines.Any(l=>l.LineAmount.HasValue)?lines.Sum(l=>l.LineAmount??0):null;return new(x.Id,x.SalesOrderNumber,x.CustomerId,x.CustomerCode,x.CustomerName,x.CustomerPONumber,x.CustomerPODate,x.OrderDate,x.RequiredDeliveryDate,x.Currency,x.PaymentTerms,x.BillingAddress,x.ShippingAddress,x.ContactPerson,x.ContactPhone,x.ContactEmail,x.Status,x.Priority,lines.Count,kg,pieces,sets,subtotal,x.TaxAmount,subtotal+(x.TaxAmount??0),x.CustomerRemarks,x.InternalRemarks,x.ConfirmedBy,x.ConfirmedOn,x.CancelledBy,x.CancelledOn,x.CancellationReason,x.CreatedBy,x.CreatedOn,x.ModifiedBy,x.ModifiedOn,Convert.ToBase64String(x.RowVersion),lines);}
}




