using CoilManager.Application.DTOs.LaminationJobs;
using CoilManager.Shared.Pagination;

namespace CoilManager.Application.Interfaces.Services;
public interface ILaminationJobService
{
 Task<PagedResult<LaminationJobListItemDto>> GetAsync(LaminationJobQueryRequest request,CancellationToken token=default); Task<LaminationJobDetailsDto> GetAsync(Guid id,CancellationToken token=default); Task<LaminationJobDetailsDto> GetByNumberAsync(string number,CancellationToken token=default); Task<string> GetNextNumberAsync(CancellationToken token=default); Task<LaminationJobDetailsDto> CreateAsync(CreateLaminationJobRequest request,CancellationToken token=default); Task<LaminationJobDetailsDto> UpdateAsync(Guid id,UpdateLaminationJobRequest request,CancellationToken token=default); Task DeleteAsync(Guid id,CancellationToken token=default); Task<IReadOnlyList<LaminationMaterialRequirementDto>> RequirementsAsync(Guid id,CancellationToken token=default); Task<IReadOnlyList<AvailableSlitCoilDto>> AvailableAsync(Guid id,AvailableSlitCoilQueryRequest request,CancellationToken token=default); Task<IReadOnlyList<LaminationJobMaterialAllocationDto>> AllocationsAsync(Guid id,CancellationToken token=default); Task<LaminationJobMaterialAllocationDto> AllocateAsync(Guid id,CreateLaminationAllocationRequest request,CancellationToken token=default); Task ReleaseAllocationAsync(Guid id,Guid allocationId,CancellationToken token=default); Task<LaminationJobDetailsDto> ConfirmAsync(Guid id,ConfirmLaminationAllocationRequest request,CancellationToken token=default); Task<LaminationJobDetailsDto> ReleaseAsync(Guid id,ReleaseLaminationJobRequest request,CancellationToken token=default); Task<LaminationJobDetailsDto> CancelAsync(Guid id,CancellationToken token=default); Task<LaminationJobDetailsDto> CompleteAsync(Guid id,CompleteLaminationJobRequest request,CancellationToken token=default); Task<LaminationCompletionDto> CompletionAsync(Guid id,CancellationToken token=default); Task<LaminationMetricsDto> MetricsAsync(CancellationToken token=default);
 Task SetDrawingAsync(Guid id,string fileName,string reference,CancellationToken token=default); Task<(string Name,string Reference)> GetDrawingAsync(Guid id,CancellationToken token=default); Task<string?> DeleteDrawingAsync(Guid id,CancellationToken token=default);
}
public interface IMaterialAllocationService : ILaminationJobService { }
