import { Component, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox'; import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../../core/auth/auth.service';

const imports=[CommonModule,ReactiveFormsModule,RouterLink,MatButtonModule,MatCardModule,MatCheckboxModule,MatFormFieldModule,MatIconModule,MatInputModule,MatProgressSpinnerModule];
@Component({selector:'app-login',imports,template:`<main class="auth-page"><mat-card class="auth-card"><div class="brand"><img src="coil-mark.svg" alt=""><div><h1>Welcome back</h1><p>Sign in to Coil Manager ERP</p></div></div><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="email" autocomplete="username"><mat-icon matSuffix>mail</mat-icon></mat-form-field><mat-form-field appearance="outline"><mat-label>Password</mat-label><input matInput [type]="show()?'text':'password'" formControlName="password" autocomplete="current-password"><button mat-icon-button matSuffix type="button" (click)="show.set(!show())"><mat-icon>{{show()?'visibility_off':'visibility'}}</mat-icon></button></mat-form-field><div class="form-row"><mat-checkbox formControlName="rememberMe">Remember me</mat-checkbox><a routerLink="/auth/forgot-password">Forgot password?</a></div>@if(error()){<p class="error" role="alert">{{error()}}</p>}<button mat-flat-button class="primary" [disabled]="form.invalid||busy()">@if(busy()){<mat-spinner diameter="20"/>} @else { Continue securely }</button></form></mat-card></main>`,styleUrl:'./auth-pages.scss'})
export class LoginComponent { private auth=inject(AuthService);private router=inject(Router);busy=signal(false);error=signal('');show=signal(false);form=new FormGroup({email:new FormControl('',[Validators.required,Validators.email]),password:new FormControl('',Validators.required),rememberMe:new FormControl(false,{nonNullable:true})});submit(){if(this.form.invalid)return;this.busy.set(true);const v=this.form.getRawValue();this.auth.login(v.email!,v.password!,v.rememberMe).subscribe({next:()=>void this.router.navigateByUrl('/dashboard'),error:e=>{this.error.set(e.error?.message??'Unable to sign in.');this.busy.set(false);}});}}

@Component({selector:'app-otp',imports,template:`<main class="auth-page"><mat-card class="auth-card"><mat-icon class="hero-icon">verified_user</mat-icon><h1>Verify your identity</h1><p>Enter the six-digit code sent to {{challenge()?.maskedEmail}}.</p><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>Verification code</mat-label><input matInput inputmode="numeric" maxlength="6" formControlName="code" autocomplete="one-time-code" class="otp"></mat-form-field>@if(error()){<p class="error" role="alert">{{error()}}</p>}<button mat-flat-button class="primary" [disabled]="form.invalid||busy()">Verify and sign in</button><button mat-button type="button" [disabled]="remaining()>0" (click)="resend()">{{remaining()>0?'Resend in '+remaining()+'s':'Resend code'}}</button></form></mat-card></main>`,styleUrl:'./auth-pages.scss'})
export class OtpComponent {private auth=inject(AuthService);private router=inject(Router);private route=inject(ActivatedRoute);challenge=signal<any>(JSON.parse(sessionStorage.getItem('cm.challenge')??'null'));busy=signal(false);error=signal('');remaining=signal(this.challenge()?.resendAfterSeconds??0);form=new FormGroup({code:new FormControl('',[Validators.required,Validators.pattern(/^\d{6}$/)])});constructor(){const timer=setInterval(()=>{this.remaining.update(x=>Math.max(0,x-1));if(!this.challenge())clearInterval(timer);},1000);}submit(){if(this.form.invalid||!this.challenge())return;this.busy.set(true);this.auth.verify(this.challenge().challengeId,this.form.value.code!).subscribe({next:()=>void this.router.navigateByUrl(this.route.snapshot.queryParamMap.get('returnUrl')??'/dashboard'),error:e=>{this.error.set(e.error?.message??'Invalid or expired code.');this.busy.set(false);}});}resend(){this.auth.resend(this.challenge().challengeId).subscribe(x=>{this.challenge.set(x.data);sessionStorage.setItem('cm.challenge',JSON.stringify(x.data));this.remaining.set(x.data.resendAfterSeconds);});}}

@Component({selector:'app-forgot',imports,template:`<main class="auth-page"><mat-card class="auth-card"><h1>Reset password</h1><p>We will send password reset instructions if the account exists.</p><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"></mat-form-field>@if(sent()){<p class="success">Check your inbox for the next step.</p>}<button mat-flat-button class="primary" [disabled]="form.invalid">Send instructions</button><a mat-button routerLink="/auth/login">Back to sign in</a></form></mat-card></main>`,styleUrl:'./auth-pages.scss'})
export class ForgotPasswordComponent {private auth=inject(AuthService);sent=signal(false);form=new FormGroup({email:new FormControl('',[Validators.required,Validators.email])});submit(){this.auth.forgotPassword(this.form.value.email!).subscribe({next:()=>this.sent.set(true),error:()=>this.sent.set(true)});}}

@Component({selector:'app-reset',imports,template:`<main class="auth-page"><mat-card class="auth-card"><h1>Choose a new password</h1><p>Use at least 12 characters with upper/lower case, number and symbol.</p><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>New password</mat-label><input matInput type="password" formControlName="password" autocomplete="new-password"></mat-form-field><mat-form-field appearance="outline"><mat-label>Confirm password</mat-label><input matInput type="password" formControlName="confirm" autocomplete="new-password"></mat-form-field>@if(error()){<p class="error">{{error()}}</p>}<button mat-flat-button class="primary" [disabled]="form.invalid">Reset password</button></form></mat-card></main>`,styleUrl:'./auth-pages.scss'})
export class ResetPasswordComponent {private auth=inject(AuthService);private route=inject(ActivatedRoute);private router=inject(Router);error=signal('');form=new FormGroup({password:new FormControl('',[Validators.required,Validators.minLength(12)]),confirm:new FormControl('',Validators.required)});submit(){const email=this.route.snapshot.queryParamMap.get('email')??'',token=this.route.snapshot.queryParamMap.get('token')??'';if(this.form.value.password!==this.form.value.confirm){this.error.set('Passwords do not match.');return;}this.auth.resetPassword(email,token,this.form.value.password!).subscribe({next:()=>void this.router.navigate(['/auth/login'],{queryParams:{reset:'success'}}),error:e=>this.error.set(e.error?.message??'Reset link is invalid or expired.')});}}

@Component({selector:'app-access-state',imports:[RouterLink,MatButtonModule,MatCardModule,MatIconModule],template:`<main class="auth-page"><mat-card class="auth-card state"><mat-icon class="hero-icon">{{icon}}</mat-icon><h1>{{title}}</h1><p>{{message}}</p><a mat-flat-button routerLink="/dashboard">Return to dashboard</a></mat-card></main>`,styleUrl:'./auth-pages.scss'})
export class AccessStateComponent {title='Access denied';message='You do not have permission to view this page. Contact an administrator if you need access.';icon='lock';}
